import os
import re
from datetime import datetime, timezone

from vector_lake.evidence_foundation import (
    EXTRACTOR_NAME,
    EXTRACTOR_VERSION,
    build_extraction_run,
    evidence_independence,
    resolve_source_artifact,
    source_locator_for,
    version_family_id,
)
from vector_lake.wiki_utils import stable_short_id, normalize_raw_ref, normalize_sources
from vector_lake.schema_validator import validate_schema, SchemaViolationException
from vector_lake.source_references import canonical_source_page_for_ref
from vector_lake.timeline_semantics import parse_timeline_prefix
from vector_lake.operational_memory_contract import is_operational_source_marker
import logging

log = logging.getLogger("vector-lake-claim-extractor")

_NON_CLAIM_ARTIFACTS = (
    (
        "system_directive",
        re.compile(
            r"^(?:\([^)]{1,100}\)\s*)?\*?\[system directive:[^\]]+\]\*?\.?$",
            re.IGNORECASE,
        ),
    ),
    (
        "generated_stub",
        re.compile(
            r"^this is an auto-generated stub page to prevent broken links from .+?\.?$",
            re.IGNORECASE,
        ),
    ),
    (
        # Same sentence with the "from X" target dropped. It still says nothing,
        # so treating it as a claim publishes a maintenance notice as knowledge.
        "generated_stub_truncated",
        re.compile(
            r"^this is an auto-generated stub page to prevent broken links\.?$",
            re.IGNORECASE,
        ),
    ),
    (
        # Alternate wording emitted by the link-repair pass; the third known
        # spelling, and the one that produced dated Observation events.
        "generated_broken_link_stub",
        re.compile(
            r"^auto-generated stub to resolve broken link from .+?\.?$",
            re.IGNORECASE,
        ),
    ),
    (
        "generated_reshaped_stub",
        re.compile(
            r"^auto-generated stub for (?P<subject>[^.!?。！？]{1,160})\. "
            r"\(last reshaped: \d{4}-\d{2}-\d{2}\)$",
            re.IGNORECASE,
        ),
    ),
    (
        "generated_entity_stub",
        re.compile(
            r"^(?P<subject>[^.!?。！？]{1,160}) auto-generated stub\.$",
            re.IGNORECASE,
        ),
    ),
    (
        "schema_migration_marker",
        re.compile(
            r"^(?:\[[^\]]+\]\s*){0,2}node auto-migrated to v\d+(?:\.\d+)* schema\.?$",
            re.IGNORECASE,
        ),
    ),
    ("decoder_metadata", re.compile(r"^read mode:\s*utf-8(?:-ignore)?\s*$", re.IGNORECASE)),
    (
        "semantic_summary_placeholder",
        re.compile(
            r"^(?:\(semantic summary\)\s*)?\(?to be generated by llm during review/synthesis\)?$",
            re.IGNORECASE,
        ),
    ),
)

def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _stable_id(prefix: str, value: str) -> str:
    """Persisted identifier family; single implementation lives in the base layer."""
    return stable_short_id(prefix, value)


def _jsonable(value):
    if hasattr(value, "isoformat"):
        try:
            return value.isoformat()
        except TypeError:
            return str(value)
    if isinstance(value, list):
        return [_jsonable(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    return value


def _collapse_text(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def _body_summary(body: str, limit: int = 320) -> str:
    return _collapse_text(body)[:limit]


def _heading_to_text(line: str) -> str:
    return re.sub(r"^#+\s*", "", line).strip()


def _clean_claim_text(text: str, limit: int = 360) -> str:
    cleaned = _collapse_text(text)
    # Strip inline sources completely to reduce RAG noise
    cleaned = re.sub(r"\(Source[s]?:\s*(.*?)\)", "", cleaned, flags=re.IGNORECASE)
    # Strip typed links first: [predicate:: [[Target|Alias]]] -> Alias or [predicate:: [[Target]]] -> Target
    cleaned = re.sub(r"\[([^\[\]]+?)::\s*\[\[([^\]|]+)\|([^\]]+)\]\]\]", r"\3", cleaned)
    cleaned = re.sub(r"\[([^\[\]]+?)::\s*\[\[(.*?)\]\]\]", r"\2", cleaned)
    # Then strip legacy links
    cleaned = re.sub(r"\[\[([^\]|]+)\|([^\]]+)\]\]", r"\2", cleaned)
    cleaned = re.sub(r"\[\[([^\]]+)\]\]", r"\1", cleaned)
    return cleaned[:limit]


def classify_non_claim_text(
    raw_text: str, cleaned_text: str = "", *, page_key: str = "",
) -> str | None:
    """Recognize whole-block maintenance prose; entity stubs require page identity."""
    text = _collapse_text(cleaned_text or raw_text)
    for reason, pattern in _NON_CLAIM_ARTIFACTS:
        match = pattern.fullmatch(text)
        if not match:
            continue
        if "subject" in match.groupdict():
            page = str(page_key or "").replace("\\", "/").rsplit("/", 1)[-1]
            if page.endswith(".md"):
                page = page[:-3]
            short_page = re.sub(
                r"^(?:Concept|Product|Institution|Event|Policy|Vendor|Entity|Source)_",
                "", page,
            )
            subject = _collapse_text(match.group("subject").replace("_", " ")).casefold()
            identities = {
                _collapse_text(value.replace("_", " ")).casefold()
                for value in (page, short_page) if value
            }
            if subject not in identities:
                continue
        return reason
    return None


# Maintenance prefixes that can precede an otherwise whole-block stub notice: a
# Timeline date/tag prefix, stray bracket tags, and a bare leading date+colon.
_LEADING_TAG = re.compile(r"^\[[^\]\r\n]{1,40}\]\s*")
_LEADING_DATE = re.compile(r"^(?:19|20)\d{2}(?:-\d{2}(?:-\d{2})?)?\s*[:：]\s*")


def classify_maintenance_only_text(
    raw_text: str, cleaned_text: str = "", *, page_key: str = "",
) -> str | None:
    """Classify maintenance prose that carries a Timeline/bullet prefix.

    ``classify_non_claim_text`` anchors every pattern to the whole block, so a
    stub notice pasted into a Task bullet (``- [2026-06-01] [Observation] ...``)
    or tagged as ``[concept] 2026-06-01: ...`` never matched and was extracted as
    a claim, producing synthetic Observation events. Stripping only leading
    date/tag prefixes before matching keeps the anchored patterns authoritative.
    """
    text = str(cleaned_text or raw_text or "").strip()
    if not text:
        return None
    direct = classify_non_claim_text(text, page_key=page_key)
    if direct:
        return direct
    prefix = parse_timeline_prefix(text)
    if prefix.event_date and prefix.description:
        text = prefix.description.strip()
    for _ in range(4):
        stripped = _LEADING_TAG.sub("", text)
        stripped = _LEADING_DATE.sub("", stripped)
        if stripped == text:
            break
        text = stripped.strip()
    if not text or text == str(cleaned_text or raw_text or "").strip():
        return None
    return classify_non_claim_text(text, page_key=page_key)


def _is_non_claim_block(raw_text: str, cleaned_text: str, *, page_key: str = "") -> bool:
    raw = str(raw_text or "").strip()
    if classify_non_claim_text(raw, cleaned_text, page_key=page_key):
        return True
    if classify_maintenance_only_text(raw, cleaned_text, page_key=page_key):
        return True
    if re.match(r"^\[\^[^\]]+\]:", raw):
        return True
    return False


def _claim_identity(
    *, page_key: str, cleaned_text: str, block_index: int, frontmatter: dict,
) -> str:
    """Return the stable claim identity for one cleaned block.

    Kept in one place so the dedupe guard and the record builder cannot drift:
    ``claim_id`` depends on the page key plus the cleaned text only, while
    ``claim_family_id`` also folds in heading and block index.
    """
    declared = frontmatter.get("claim_id") if block_index == 1 else None
    return declared or _stable_id("claim", f"{page_key}:{cleaned_text}")


def _iter_blocks(body: str, *, page_key: str = "") -> list[dict]:
    import mistune
    markdown = mistune.create_markdown(renderer='ast')
    ast = markdown(body or "")
    
    blocks = []
    current_heading = None

    def extract_text(node) -> str:
        if isinstance(node, dict):
            if node.get("type") == "block_code":
                return " "
            if node.get("type") in ("softbreak", "hardbreak"):
                return " "
            text = node.get("raw", "")
            for child in node.get("children", []):
                text += extract_text(child)
            return text
        return ""

    def process_node(node):
        nonlocal current_heading
        if node["type"] == "heading":
            current_heading = extract_text(node).strip()
        elif node["type"] == "paragraph":
            raw_text = extract_text(node).strip()
            text = _clean_claim_text(raw_text)
            if text and not _is_non_claim_block(raw_text, text, page_key=page_key):
                blocks.append({
                    "kind": "paragraph",
                    "heading": current_heading,
                    "text": text,
                    "raw_text": raw_text,
                })
        elif node["type"] == "list":
            for child in node.get("children", []):
                if child["type"] == "list_item":
                    raw_text = extract_text(child).strip()
                    text = _clean_claim_text(raw_text)
                    if text and not _is_non_claim_block(raw_text, text, page_key=page_key):
                        blocks.append({
                            "kind": "bullet",
                            "heading": current_heading,
                            "text": text,
                            "raw_text": raw_text,
                        })

    for node in ast:
        process_node(node)

    return blocks


def _claim_type_for_block(kind: str) -> str:
    if kind == "bullet":
        return "bullet-claim"
    return "assertion"


def _validity_defaults(frontmatter: dict) -> dict:
    return {
        "valid_from": _jsonable(frontmatter.get("valid_from")),
        "valid_to": _jsonable(frontmatter.get("valid_to")),
        "review_after": _jsonable(frontmatter.get("review_after")),
        "freshness_tier": frontmatter.get("freshness_tier", "unknown"),
        "temporal_anchor": frontmatter.get("temporal_anchor"),
        "memory_type": frontmatter.get("memory_type"),
        "memory_key": frontmatter.get("memory_key"),
        "authority_score": frontmatter.get("authority_score"),
        "importance_score": frontmatter.get("importance_score"),
        "reinforcement_count": frontmatter.get("reinforcement_count"),
        "ttl_days": frontmatter.get("ttl_days") or frontmatter.get("ttl"),
        "authoring_origin": frontmatter.get("authoring_origin"),
    }


_SOURCE_BINDING_CONFLICT = "conflicting source identity bindings"
_SOURCE_CONFIG_CONFLICT = "conflicting source configuration bindings"


def _bind_source_refs(pairs: list[tuple[str, str]]) -> list[tuple[str, str]]:
    """Keep legacy identity while retaining one truthful physical reference."""
    bindings: dict[str, tuple[str, str]] = {}
    for identity_ref, physical_ref in pairs:
        physical_key = normalize_raw_ref(physical_ref)
        previous = bindings.get(identity_ref)
        if previous and previous[0] != physical_key:
            raise ValueError(_SOURCE_BINDING_CONFLICT)
        if not previous:
            bindings[identity_ref] = (physical_key, physical_ref)
    return [(identity, physical) for identity, (_, physical) in bindings.items()]


def _source_config(config: dict, physical_ref: str, identity_ref: str):
    physical_present = physical_ref in config
    legacy_present = identity_ref in config
    if physical_present and legacy_present and physical_ref != identity_ref:
        if config[physical_ref] != config[identity_ref]:
            raise ValueError(_SOURCE_CONFIG_CONFLICT)
    if physical_present:
        return config[physical_ref]
    if legacy_present:
        return config[identity_ref]
    return None


def extract_page_objects(
    page_path: str,
    frontmatter: dict,
    body: str,
    *,
    entity_only: bool = False,
) -> dict:
    now = _utc_now()
    page_name = os.path.basename(page_path)
    page_key = os.path.splitext(page_name)[0]
    title = frontmatter.get("title", page_key)
    page_type = str(frontmatter.get("type", "concept")).lower()
    aliases = frontmatter.get("aliases") or []
    if isinstance(aliases, str):
        aliases = [aliases]
    aliases = [str(alias).strip() for alias in aliases if alias and str(alias).strip()]
    raw_frontmatter_sources = frontmatter.get("sources") or []
    if isinstance(raw_frontmatter_sources, str):
        raw_frontmatter_sources = [raw_frontmatter_sources]
    raw_frontmatter_sources = [
        str(value).strip() for value in raw_frontmatter_sources
        if value and str(value).strip()
    ]
    sources = normalize_sources(raw_frontmatter_sources)
    summary = frontmatter.get("summary") or _body_summary(body)
    validity_defaults = _validity_defaults(frontmatter)

    try:
        validate_schema(frontmatter, body, page_name)
    except SchemaViolationException as e:
        log.warning(f"Validation failed for {page_name}, skipping extraction: {e}")
        return {
            "entities": [],
            "claims": [],
            "evidence": [],
            "sources": [],
            "edges": [],
            "page_key": page_key,
            "page_type": page_type,
        }

    def _parse_original_inline_sources(raw_text: str):
        found_sources = []
        for match in re.finditer(r"\(Source[s]?:\s*(.*?)\)", raw_text, flags=re.IGNORECASE):
            content = match.group(1)
            for m2 in re.finditer(r"\[\[(.*?)\]\]", content):
                found_sources.append(m2.group(1).split("|")[0].strip())
        return found_sources

    def _parse_inline_sources(raw_text: str):
        # Retain the legacy lossy normalization for source/evidence identity.
        return [value.replace(".md", "") for value in _parse_original_inline_sources(raw_text)]

    subject_entity_ids = []
    entity_records = []
    source_records = []
    evidence_records = []
    claim_records = []

    clean_body = re.sub(r"```.*?```", "", body, flags=re.DOTALL)
    clean_body = re.sub(r"`.*?`", "", clean_body)
    triples = []
    links = set()
    page_edges = []
    for match in re.finditer(r"\[([^\[\]]+?)::\s*\[\[(.*?)\]\]\]", clean_body):
        predicate = match.group(1).strip()
        target = match.group(2).split("|")[0].strip().replace(".md", "")
        if target:
            links.add(target)
            triples.append({"predicate": predicate, "target": target})
            page_edges.append({
                "source_id": page_key,
                "target_id": target,
                "relation": predicate,
                "weight": 1.0,
                "updated_at": now,
            })

    entity_id = frontmatter.get("entity_id") or _stable_id("entity", page_key)
    subject_entity_ids.append(entity_id)
    entity_records.append({
        "entity_id": entity_id,
        "id": frontmatter.get("id") or entity_id,
        "page_key": page_key,
        "canonical_name": title,
        "title": title,
        "type": page_type,
        "entity_type": page_type,
        "status": frontmatter.get("status", "Active"),
        "epistemic-status": frontmatter.get("epistemic-status", "draft"),
        "aliases": aliases,
        "domain": frontmatter.get("domain", "General"),
        "topic_cluster": frontmatter.get("topic_cluster", "General"),
        "categories": _jsonable(frontmatter.get("categories", [])),
        "tags": _jsonable(frontmatter.get("tags", [])),
        "sources": sources,
        "tension_edges": _jsonable(frontmatter.get("tension_edges", [])),
        "relations": _jsonable(frontmatter.get("relations", [])),
        "links": sorted(links),
        "outbound_links": sorted(links),
        "triples": triples,
        "summary": summary,
        "raw_text": body,
        "ttl": frontmatter.get("ttl"),
        "created_at": _jsonable(frontmatter.get("created", now)),
        "updated": _jsonable(frontmatter.get("updated", now)),
        "updated_at": _jsonable(frontmatter.get("updated", now)),
        "source_page": page_name,
    })

    if entity_only:
        return {
            "entities": entity_records,
            "claims": [],
            "evidence": [],
            "sources": [],
            "source_artifacts": [],
            "extraction_runs": [],
            "edges": page_edges,
            "page_key": page_key,
            "page_type": page_type,
        }

    blocks = _iter_blocks(body, page_key=page_key)
    if not blocks and summary:
        blocks = [{
            "kind": "paragraph",
            "heading": title,
            "text": summary,
        }]

    inline_source_pairs = []
    for block in blocks:
        raw_text = block.get("raw_text", block.get("text", ""))
        originals = _parse_original_inline_sources(raw_text)
        inline_source_pairs.extend((value.replace(".md", ""), value) for value in originals)
    frontmatter_pairs = [
        (normalize_sources([raw_ref])[0], raw_ref)
        for raw_ref in raw_frontmatter_sources
    ]
    source_bindings = _bind_source_refs([*frontmatter_pairs, *inline_source_pairs])
    physical_ref_by_identity = dict(source_bindings)
    source_metadata = frontmatter.get("source_artifacts") or {}
    if not isinstance(source_metadata, dict):
        source_metadata = {}
    artifact_by_source_id = {}
    source_id_by_ref = {}
    source_artifact_records = []
    source_locators = frontmatter.get("source_locators") or {}
    if not isinstance(source_locators, dict):
        source_locators = {}
    locator_frontmatter = dict(frontmatter)
    locator_map = dict(source_locators)
    metadata_by_physical_ref = {}
    for identity_ref, physical_ref in source_bindings:
        metadata_by_physical_ref[physical_ref] = _source_config(
            source_metadata, physical_ref, identity_ref
        )
        locator = _source_config(source_locators, physical_ref, identity_ref)
        if locator is not None:
            locator_map[physical_ref] = locator
    locator_frontmatter["source_locators"] = locator_map
    for identity_ref, physical_ref in source_bindings:
        source_id = _stable_id("source", identity_ref)
        source_id_by_ref[identity_ref] = source_id
        metadata = metadata_by_physical_ref[physical_ref] or {}
        if not isinstance(metadata, dict):
            metadata = {}
        artifact = resolve_source_artifact(physical_ref, source_id=source_id, metadata=metadata)
        artifact_by_source_id[source_id] = artifact
        source_artifact_records.append(artifact)
        source_records.append({
            "source_id": source_id,
            "artifact_id": artifact["artifact_id"],
            "raw_ref": artifact["raw_ref"],
            "canonical_source_page": canonical_source_page_for_ref(
                physical_ref,
                owning_page=page_name if page_type == "source" else "",
            ),
            "source_type": os.path.splitext(physical_ref)[1].lstrip(".").lower() or "md",
            "title": title if page_type == "source" else os.path.basename(physical_ref),
            "ingested_at": now,
            "content_hash": artifact["content_hash"],
            "hash_algorithm": artifact["hash_algorithm"],
            "byte_size": artifact["byte_size"],
            "mime_type": artifact["mime_type"],
            "storage_uri": artifact["storage_uri"],
            "integrity_status": artifact["integrity_status"],
            "classification": artifact["classification"],
            "retention_policy": artifact["retention_policy"],
            "legal_hold": artifact["legal_hold"],
            "lineage_id": artifact["lineage_id"],
            "generation_parent_refs": artifact["generation_parent_refs"],
        })
    source_ids = [source_id_by_ref[raw_ref] for raw_ref in sources]
    extraction_run = build_extraction_run(
        page_key=page_key,
        body=body,
        artifact_ids=[record["artifact_id"] for record in source_artifact_records],
        frontmatter=frontmatter,
    )
    extraction_run["recorded_at"] = now
    confidence_kind = "declared" if "confidence" in frontmatter else "legacy_prior"
    calibrated_probability = (
        frontmatter.get("confidence")
        if frontmatter.get("confidence_calibrated") is True
        else None
    )

    seen_claim_ids: set[str] = set()

    for block_index, block in enumerate(blocks, start=1):
        timeline_prefix = parse_timeline_prefix(block["text"])
        block_temporal = timeline_prefix.event_date
        # Preserve the established identity behavior for legacy coarse dates.
        # Full dates were previously canonical text, so adding their metadata
        # must not change claim_text or claim_id.
        cleaned_text = block["text"]
        if timeline_prefix.precision in {"year", "month", "quarter", "half"}:
            # Baseline canonicalization removed only the coarse date.  Keep a
            # following tag because it participates in stable claim identity.
            cleaned_text = re.sub(
                rf"^\[{re.escape(timeline_prefix.event_date)}\]\s*",
                "",
                cleaned_text,
                count=1,
            )
        final_temporal = block_temporal or validity_defaults.get("temporal_anchor")

        claim_id = _claim_identity(
            page_key=page_key,
            cleaned_text=cleaned_text,
            block_index=block_index,
            frontmatter=frontmatter,
        )
        if claim_id in seen_claim_ids:
            # One identity is one knowledge unit. A page that repeats the same
            # sentence yields two blocks with one claim_id; emitting both put a
            # conflicting duplicate in the change set and aborted the whole apply
            # batch. First occurrence wins, and nothing is emitted for the repeat.
            continue
        seen_claim_ids.add(claim_id)

        raw_text = block.get("raw_text", block["text"])
        inline_sources = _parse_inline_sources(raw_text)
        original_inline_sources = _parse_original_inline_sources(raw_text)

        custom_claim_type = _claim_type_for_block(block["kind"])
        heading = block.get("heading") or title
        heading_lower = (heading or "").lower()
        if any(k in heading_lower for k in ["编译事实", "compiled truth", "事实", "truth"]):
            custom_claim_type = "compiled-truth"
        elif any(k in heading_lower for k in ["证据时间线", "timeline", "证据", "时间线"]):
            custom_claim_type = "timeline-event"
            
        combined_sources = list(dict.fromkeys([*sources, *inline_sources]))
        combined_source_ids = [source_id_by_ref[raw_ref] for raw_ref in combined_sources]
        operational_memory_provenance = any(
            is_operational_source_marker(raw_ref)
            for raw_ref in [*raw_frontmatter_sources, *original_inline_sources]
        )

        evidence_ids = []
        for raw_ref, source_id in zip(combined_sources, combined_source_ids):
            if len(sources) > 1 and page_type != "source" and raw_ref not in inline_sources:
                continue
            evidence_id = _stable_id("evidence", f"{page_key}:{raw_ref}:{cleaned_text}")
            evidence_ids.append(evidence_id)
            projection_locator = {
                "page_key": page_key,
                "heading": block.get("heading") or title,
                "block_index": block_index,
            }
            artifact = artifact_by_source_id[source_id]
            physical_ref = physical_ref_by_identity[raw_ref]
            evidence_records.append({
                "evidence_id": evidence_id,
                "evidence_family_id": version_family_id(
                    "evidencefamily",
                    page_key,
                    {
                        **projection_locator,
                        "source_id": source_id,
                        "kind": f"block-{block['kind']}",
                    },
                ),
                "source_id": source_id,
                "artifact_id": artifact["artifact_id"],
                "locator": projection_locator,
                "projection_locator": projection_locator,
                "source_locator": source_locator_for(
                    locator_frontmatter,
                    physical_ref,
                    artifact=artifact,
                ),
                "evidence_text": cleaned_text,
                "evidence_type": f"block-{block['kind']}",
                "created_at": now,
                "extraction_run_id": extraction_run["run_id"],
                **evidence_independence(
                    physical_ref,
                    page_name,
                    artifact["generation_parent_refs"],
                ),
                "supports_claim_ids": [],
                "contradicts_claim_ids": [],
            })

        from vector_lake.wiki_utils import enforce_claim_dict
        claim_locator = {
            "page_key": page_key,
            "heading": block.get("heading") or title,
            "block_index": block_index,
        }
        claim_record = enforce_claim_dict({
            "claim_id": claim_id,
            "claim_family_id": version_family_id("claimfamily", page_key, claim_locator),
            "claim_text": cleaned_text,
            "claim_type": custom_claim_type,
            "claim_scope": "block",
            "status": frontmatter.get("status", "Active"),
            "confidence": frontmatter.get("confidence", 0.6 if page_type == "synthesis" else 0.8),
            "confidence_kind": confidence_kind,
            "calibrated_probability": calibrated_probability,
            "assessment_status": "unreviewed",
            "extractor_name": EXTRACTOR_NAME,
            "extractor_version": EXTRACTOR_VERSION,
            "extraction_run_id": extraction_run["run_id"],
            "subject_entity_ids": list(subject_entity_ids),
            "evidence_ids": evidence_ids,
            "source_ids": list(combined_source_ids),
            "inline_sources": inline_sources,
            "locator": claim_locator,
            **validity_defaults,
            "temporal_anchor": final_temporal,
            "event_date": block_temporal,
            "event_tag": timeline_prefix.event_tag,
            "created_at": _jsonable(frontmatter.get("created", now)),
            "updated_at": _jsonable(frontmatter.get("updated", now)),
            "source_page": page_name,
            "operational_memory_provenance": operational_memory_provenance,
        })
        claim_records.append(claim_record)
        if evidence_ids:
            for evidence_record in evidence_records[-len(evidence_ids):]:
                evidence_record["supports_claim_ids"].append(claim_id)

    if summary:
        summary_prefix = parse_timeline_prefix(summary)
        summary_temporal = summary_prefix.event_date
        cleaned_summary = summary
        if summary_prefix.precision in {"year", "month", "quarter", "half"}:
            cleaned_summary = re.sub(
                rf"^\[{re.escape(summary_prefix.event_date)}\]\s*",
                "",
                cleaned_summary,
                count=1,
            )
        final_summary_temporal = summary_temporal or validity_defaults.get("temporal_anchor")

        summary_evidence_ids = []
        for raw_ref, source_id in zip(sources, source_ids):
            evidence_id = _stable_id("evidence", f"{page_key}:summary:{raw_ref}")
            summary_evidence_ids.append(evidence_id)
            projection_locator = {"page_key": page_key, "heading": title, "block_index": 0}
            artifact = artifact_by_source_id[source_id]
            physical_ref = physical_ref_by_identity[raw_ref]
            evidence_records.append({
                "evidence_id": evidence_id,
                "evidence_family_id": version_family_id(
                    "evidencefamily",
                    page_key,
                    {**projection_locator, "source_id": source_id, "kind": "page-summary"},
                ),
                "source_id": source_id,
                "artifact_id": artifact["artifact_id"],
                "locator": projection_locator,
                "projection_locator": projection_locator,
                "source_locator": source_locator_for(
                    locator_frontmatter,
                    physical_ref,
                    artifact=artifact,
                ),
                "evidence_text": cleaned_summary,
                "evidence_type": "page-summary",
                "created_at": now,
                "extraction_run_id": extraction_run["run_id"],
                **evidence_independence(
                    physical_ref,
                    page_name,
                    artifact["generation_parent_refs"],
                ),
                "supports_claim_ids": [],
                "contradicts_claim_ids": [],
            })

        summary_claim_id = _stable_id("claim", f"{page_key}:summary:{cleaned_summary}")
        summary_locator = {"page_key": page_key, "heading": title, "block_index": 0}
        summary_claim = enforce_claim_dict({
            "claim_id": summary_claim_id,
            "claim_family_id": version_family_id("claimfamily", page_key, summary_locator),
            "claim_text": cleaned_summary,
            "claim_type": "summary",
            "claim_scope": "page",
            "status": frontmatter.get("status", "Active"),
            "confidence": frontmatter.get("confidence", 0.65 if page_type == "synthesis" else 0.82),
            "confidence_kind": confidence_kind,
            "calibrated_probability": calibrated_probability,
            "assessment_status": "unreviewed",
            "extractor_name": EXTRACTOR_NAME,
            "extractor_version": EXTRACTOR_VERSION,
            "extraction_run_id": extraction_run["run_id"],
            "subject_entity_ids": list(subject_entity_ids),
            "evidence_ids": summary_evidence_ids,
            "source_ids": list(source_ids),
            "locator": summary_locator,
            **validity_defaults,
            "temporal_anchor": final_summary_temporal,
            "event_date": summary_temporal,
            "event_tag": summary_prefix.event_tag,
            "created_at": _jsonable(frontmatter.get("created", now)),
            "updated_at": _jsonable(frontmatter.get("updated", now)),
            "source_page": page_name,
            "operational_memory_provenance": any(
                is_operational_source_marker(raw_ref) for raw_ref in raw_frontmatter_sources
            ),
        })
        if summary_evidence_ids:
            claim_records.append(summary_claim)
            for evidence_record in evidence_records[-len(summary_evidence_ids):]:
                evidence_record["supports_claim_ids"].append(summary_claim_id)

    return {
        "entities": entity_records,
        "claims": claim_records,
        "evidence": evidence_records,
        "sources": source_records,
        "source_artifacts": source_artifact_records,
        "extraction_runs": [extraction_run],
        "edges": page_edges,
        "page_key": page_key,
        "page_type": page_type,
    }

