"""Deterministic duplicate-candidate analysis shared by governance and lint."""

from __future__ import annotations

import hashlib
import re
import unicodedata
from collections import defaultdict
from difflib import SequenceMatcher
from itertools import combinations
from pathlib import Path


_TYPE_PREFIX = re.compile(
    r"^(?:concept|vendor|institution|product|person|event|policy|standard|source|synthesis|system)[_-]+",
    re.IGNORECASE,
)
_REVISION_HASH_SUFFIX = re.compile(r"-(?:[0-9a-f]{8})$", re.IGNORECASE)
_ARXIV_ID = re.compile(r"^\d{4}\.\d{4,5}v\d+$", re.IGNORECASE)
_GENERIC_SOURCE_MARKERS = {
    "sourceautofixed",
    "sourceautogenerated",
    "sourcegenerated",
    "sourcestub",
    "sourcetemplate",
}
_DECISION_ORDER = {"merge": 0, "alias": 1, "review": 2, "keep_separate": 3}


def strip_entity_prefix(value: str) -> str:
    text = str(value or "").strip()
    if text.casefold().endswith(".md"):
        text = text[:-3]
    return _TYPE_PREFIX.sub("", text, count=1)


def normalize_name(value: str) -> str:
    """Normalize identity text without discarding non-ASCII letters or digits."""
    text = unicodedata.normalize("NFKC", strip_entity_prefix(value)).casefold()
    return "".join(character for character in text if character.isalnum())


def _string_list(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, (str, int, float)):
        value = [value]
    if not isinstance(value, (list, tuple, set, frozenset)):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def _tokens(value: str) -> frozenset[str]:
    text = unicodedata.normalize("NFKC", strip_entity_prefix(value)).casefold()
    return frozenset(token for token in re.findall(r"[^\W_]+", text, re.UNICODE) if token)


def _stable_sources(entity: dict) -> frozenset[str]:
    values = [
        *_string_list(entity.get("sources")),
        *_string_list(entity.get("source_ids")),
    ]
    stable = set()
    for source in values:
        normalized = normalize_name(source)
        if not normalized:
            continue
        if normalized in _GENERIC_SOURCE_MARKERS:
            continue
        if any(marker in normalized for marker in ("autofixed", "autogenerated", "template", "stub")):
            continue
        stable.add(normalized)
    return frozenset(stable)


def _body_text(entity: dict) -> str:
    for field in ("raw_text", "body", "summary", "description"):
        value = entity.get(field)
        if isinstance(value, str) and value.strip():
            return re.sub(r"\s+", " ", value).strip().casefold()
    return ""


def _body_fingerprint(body: str) -> str:
    if len(body) < 40:
        return ""
    normalized = re.sub(r"\s+", " ", body).strip()
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def _revision_base(page_key: str) -> str:
    value = str(page_key or "")
    if value.casefold().endswith(".md"):
        value = value[:-3]
    return _REVISION_HASH_SUFFIX.sub("", value)


def _record(entity: dict) -> dict:
    canonical_name = str(
        entity.get("canonical_name")
        or entity.get("title")
        or entity.get("page_key")
        or entity.get("entity_id")
        or ""
    )
    aliases = _string_list(entity.get("aliases"))
    page_key = str(entity.get("page_key") or "")
    variants = [canonical_name, strip_entity_prefix(page_key), *aliases]
    norms = frozenset(filter(None, (normalize_name(value) for value in variants)))
    alias_norms = frozenset(filter(None, (normalize_name(value) for value in aliases)))
    body = _body_text(entity)
    return {
        "entity": entity,
        "entity_id": str(entity.get("entity_id") or page_key or canonical_name),
        "name": canonical_name,
        "page_key": page_key,
        "primary_norm": normalize_name(canonical_name),
        "norms": norms,
        "alias_norms": alias_norms,
        "tokens": frozenset(token for value in variants for token in _tokens(value)),
        "sources": _stable_sources(entity),
        "body": body,
        "body_fingerprint": _body_fingerprint(body),
        "revision_base": _revision_base(page_key),
    }


def _name_similarity(left: dict, right: dict) -> float:
    if not left["primary_norm"] or not right["primary_norm"]:
        return 0.0
    if left["primary_norm"] == right["primary_norm"]:
        return 1.0
    return SequenceMatcher(None, left["primary_norm"], right["primary_norm"]).ratio()


def _numeric_identity_conflict(left: dict, right: dict) -> bool:
    left_norm = left["primary_norm"]
    right_norm = right["primary_norm"]
    left_numbers = tuple(re.findall(r"\d+", left_norm))
    right_numbers = tuple(re.findall(r"\d+", right_norm))
    if left_numbers == right_numbers:
        return False
    left_surface = unicodedata.normalize(
        "NFKC",
        strip_entity_prefix(left["name"]),
    ).casefold()
    right_surface = unicodedata.normalize(
        "NFKC",
        strip_entity_prefix(right["name"]),
    ).casefold()
    if _ARXIV_ID.fullmatch(left_surface) and _ARXIV_ID.fullmatch(right_surface):
        return True
    left_lead = re.match(r"^[^\d]+", left_surface)
    right_lead = re.match(r"^[^\d]+", right_surface)
    if left_lead and right_lead:
        left_prefix = re.sub(r"\W+", "", left_lead.group(0))
        right_prefix = re.sub(r"\W+", "", right_lead.group(0))
        if left_prefix and left_prefix == right_prefix:
            return True
    left_base = re.sub(r"\d+", "", left_norm)
    right_base = re.sub(r"\d+", "", right_norm)
    return bool(
        left_base
        and (
            left_base == right_base
            or left_base.startswith(right_base)
            or right_base.startswith(left_base)
        )
    )


def _plural_equivalent(left_norm: str, right_norm: str) -> bool:
    if not left_norm or not right_norm:
        return False

    def singular(value: str) -> str:
        return value[:-1] if value.endswith("s") and not value.endswith("ss") else value

    return left_norm != right_norm and singular(left_norm) == singular(right_norm)


def _canonical_rank(record: dict) -> tuple:
    entity = record["entity"]
    status = str(entity.get("status", "")).casefold()
    status_score = 3 if status == "active" else 2 if status == "draft" else 0
    page_key_score = int(bool(record["page_key"]) and "/" not in record["page_key"] and "\\" not in record["page_key"])
    body = record["body"]
    non_stub_body = int(bool(body) and "auto-generated stub" not in body and len(body) >= 80)
    source_score = min(len(record["sources"]), 5)
    inbound_score = int(entity.get("inbound_count") or entity.get("inlinks") or 0)
    return (
        status_score,
        page_key_score,
        non_stub_body,
        source_score,
        inbound_score,
        len(body),
    )


def _evaluate_pair(left: dict, right: dict) -> dict:
    primary_exact = bool(left["primary_norm"]) and left["primary_norm"] == right["primary_norm"]
    normalized_overlap = left["norms"] & right["norms"]
    alias_overlap = left["alias_norms"] & right["alias_norms"]
    stable_source_overlap = left["sources"] & right["sources"]
    token_overlap = left["tokens"] & right["tokens"]
    similarity = _name_similarity(left, right)
    body_similarity = 0.0
    if (
        similarity >= 0.90
        and len(left["body"]) >= 40
        and len(right["body"]) >= 40
    ):
        body_similarity = SequenceMatcher(
            None,
            left["body"][:2000],
            right["body"][:2000],
        ).quick_ratio()
    content_fingerprint_match = bool(
        left["body_fingerprint"]
        and left["body_fingerprint"] == right["body_fingerprint"]
    )
    revision_suffix_match = bool(
        left["page_key"]
        and right["page_key"]
        and left["page_key"] != right["page_key"]
        and left["revision_base"] == right["revision_base"]
        and (
            _REVISION_HASH_SUFFIX.search(left["page_key"])
            or _REVISION_HASH_SUFFIX.search(right["page_key"])
        )
    )
    numeric_conflict = _numeric_identity_conflict(left, right)
    plural_equivalent = _plural_equivalent(left["primary_norm"], right["primary_norm"])
    left_type = str(left["entity"].get("type") or left["entity"].get("entity_type") or "").casefold()
    right_type = str(right["entity"].get("type") or right["entity"].get("entity_type") or "").casefold()
    type_conflict = bool(left_type and right_type and left_type != right_type)

    reasons = []
    evidence_score = round(similarity * 45)
    if primary_exact:
        reasons.append("normalized-name-match")
        evidence_score += 45
    elif normalized_overlap:
        reasons.append("normalized-variant-match")
        evidence_score += 30
    if alias_overlap:
        reasons.append("alias-overlap:" + ", ".join(sorted(alias_overlap)[:3]))
        evidence_score += 15
    if plural_equivalent:
        reasons.append("singular-plural-equivalent")
        evidence_score += 10
    if stable_source_overlap:
        reasons.append("stable-source-overlap")
        evidence_score += min(15, 5 * len(stable_source_overlap))
    if content_fingerprint_match:
        reasons.append("content-fingerprint-match")
        evidence_score += 20
    if revision_suffix_match:
        reasons.append("revision-suffix-match")
        evidence_score += 20
    if body_similarity >= 0.55:
        reasons.append(f"body-similarity:{body_similarity:.0%}")
        evidence_score += round(body_similarity * 10)
    if len(token_overlap) >= 2:
        reasons.append("token-overlap:" + ", ".join(sorted(token_overlap)[:4]))
        evidence_score += 5

    left_entity = left["entity"]
    right_entity = right["entity"]
    left_domain = str(left_entity.get("domain") or "")
    right_domain = str(right_entity.get("domain") or "")
    left_cluster = str(left_entity.get("topic_cluster") or "")
    right_cluster = str(right_entity.get("topic_cluster") or "")
    if (
        left_domain
        and left_cluster
        and left_domain.casefold() != "general"
        and left_domain == right_domain
        and left_cluster == right_cluster
    ):
        reasons.append("domain-cluster-match")
        evidence_score += 5

    if type_conflict:
        reasons.append("entity-type-conflict")

    source_identity_evidence = bool(
        stable_source_overlap
        or content_fingerprint_match
        or revision_suffix_match
        or body_similarity >= 0.90
    )

    if type_conflict and "source" in {left_type, right_type}:
        decision = "keep_separate"
        evidence_score = min(evidence_score, 25)
    elif revision_suffix_match and left_type == right_type:
        decision = "merge"
    elif numeric_conflict:
        reasons.append("numeric-identity-conflict")
        decision = "keep_separate"
        evidence_score = min(evidence_score, 35)
    elif type_conflict:
        decision = "review"
        evidence_score = min(evidence_score, 60)
    elif primary_exact and left_type == "source" and not source_identity_evidence:
        reasons.append("source-identity-evidence-missing")
        decision = "review"
        evidence_score = min(evidence_score, 70)
    elif primary_exact:
        decision = "merge"
    elif plural_equivalent and (stable_source_overlap or body_similarity >= 0.55):
        decision = "merge"
    elif similarity >= 0.96 and (
        stable_source_overlap
        or (body_similarity >= 0.80 and len(token_overlap) >= 2)
    ):
        decision = "merge"
    elif similarity >= 0.94:
        decision = "alias"
    elif alias_overlap or similarity >= 0.84:
        decision = "review"
    else:
        decision = "keep_separate"

    pair_key = "::".join(sorted((left["entity_id"], right["entity_id"])))
    return {
        "pair_key": pair_key,
        "evidence_score": min(100, max(0, evidence_score)),
        "score": min(100, max(0, evidence_score)),
        "decision": decision,
        "left_entity_id": left["entity_id"],
        "left_name": left["name"],
        "left_page_key": left["page_key"],
        "right_entity_id": right["entity_id"],
        "right_name": right["name"],
        "right_page_key": right["page_key"],
        "name_similarity": round(similarity, 4),
        "body_similarity": round(body_similarity, 4),
        "reasons": reasons,
        "domain": left_domain or right_domain or "General",
        "preflight_state": "not_run",
        "preflight_errors": [],
    }


class _UnionFind:
    def __init__(self, values):
        self.parent = {value: value for value in values}

    def find(self, value):
        parent = self.parent[value]
        if parent != value:
            self.parent[value] = self.find(parent)
        return self.parent[value]

    def union(self, left, right):
        left_root = self.find(left)
        right_root = self.find(right)
        if left_root != right_root:
            self.parent[right_root] = left_root


def _candidate_index_pairs(records: list[dict], fuzzy_threshold: float = 0.82, window: int = 16) -> set[tuple[int, int]]:
    pairs: set[tuple[int, int]] = set()
    norm_buckets: dict[str, list[int]] = defaultdict(list)
    for index, record in enumerate(records):
        for norm in record["norms"]:
            if norm:
                norm_buckets[norm].append(index)
    for indices in norm_buckets.values():
        pairs.update(combinations(sorted(set(indices)), 2))

    type_buckets: dict[tuple[str, str], list[int]] = defaultdict(list)
    for index, record in enumerate(records):
        entity_type = str(record["entity"].get("type") or record["entity"].get("entity_type") or "")
        type_buckets[
            (entity_type.casefold(), record["primary_norm"][:2])
        ].append(index)
    for indices in type_buckets.values():
        ordered = sorted(indices, key=lambda index: (records[index]["primary_norm"], records[index]["entity_id"]))
        for position, left_index in enumerate(ordered):
            left_norm = records[left_index]["primary_norm"]
            if not left_norm:
                continue
            for right_index in ordered[position + 1 : position + 1 + window]:
                right_norm = records[right_index]["primary_norm"]
                if not right_norm:
                    continue
                longer = max(len(left_norm), len(right_norm))
                if abs(len(left_norm) - len(right_norm)) > max(3, int(longer * 0.25)):
                    continue
                similarity = SequenceMatcher(None, left_norm, right_norm).ratio()
                if similarity >= fuzzy_threshold:
                    pairs.add(tuple(sorted((left_index, right_index))))
    return pairs


def analyze_entities(
    entities: list[dict],
    limit: int | None = 20,
    versions: dict[str, str] | None = None,
) -> list[dict]:
    """Return component-aware candidates with explicit merge/alias/review/keep decisions."""
    records = []
    for entity in entities:
        if str(entity.get("status", "")).casefold() == "merged":
            continue
        if str(entity.get("type") or entity.get("entity_type") or "").casefold() == "system":
            continue
        record = _record(entity)
        if record["primary_norm"]:
            records.append(record)

    record_by_id = {record["entity_id"]: record for record in records}
    evaluated = [
        _evaluate_pair(records[left_index], records[right_index])
        for left_index, right_index in sorted(_candidate_index_pairs(records))
        if records[left_index]["entity_id"] != records[right_index]["entity_id"]
    ]

    union_find = _UnionFind(record_by_id)
    for candidate in evaluated:
        if candidate["decision"] == "merge":
            union_find.union(candidate["left_entity_id"], candidate["right_entity_id"])

    components: dict[str, list[str]] = defaultdict(list)
    for entity_id in record_by_id:
        components[union_find.find(entity_id)].append(entity_id)

    merge_results = []
    merged_component_by_id = {}
    evaluated_by_pair = {candidate["pair_key"]: candidate for candidate in evaluated}
    for member_ids in components.values():
        if len(member_ids) < 2:
            continue
        ordered_members = sorted(member_ids)
        component_id = "merge_" + hashlib.sha1("::".join(ordered_members).encode("utf-8")).hexdigest()[:12]
        target_id = max(ordered_members, key=lambda entity_id: _canonical_rank(record_by_id[entity_id]))
        for entity_id in ordered_members:
            merged_component_by_id[entity_id] = component_id
        for source_id in ordered_members:
            if source_id == target_id:
                continue
            pair_key = "::".join(sorted((target_id, source_id)))
            candidate = dict(
                evaluated_by_pair.get(pair_key)
                or _evaluate_pair(record_by_id[target_id], record_by_id[source_id])
            )
            candidate.update(
                {
                    "left_entity_id": target_id,
                    "left_name": record_by_id[target_id]["name"],
                    "left_page_key": record_by_id[target_id]["page_key"],
                    "right_entity_id": source_id,
                    "right_name": record_by_id[source_id]["name"],
                    "right_page_key": record_by_id[source_id]["page_key"],
                    "decision": "review" if len(ordered_members) > 2 else "merge",
                    "component_id": component_id,
                    "component_size": len(ordered_members),
                }
            )
            if len(ordered_members) > 2 and "large-component-review" not in candidate["reasons"]:
                candidate["reasons"] = [*candidate["reasons"], "large-component-review"]
            merge_results.append(candidate)

    other_results = []
    for candidate in evaluated:
        left_component = merged_component_by_id.get(candidate["left_entity_id"])
        right_component = merged_component_by_id.get(candidate["right_entity_id"])
        if left_component and left_component == right_component:
            continue
        candidate = dict(candidate)
        candidate["component_id"] = ""
        candidate["component_size"] = 1
        other_results.append(candidate)

    versions = versions or {}
    results = merge_results + other_results
    for candidate in results:
        candidate["left_version"] = versions.get(candidate["left_page_key"], "")
        candidate["right_version"] = versions.get(candidate["right_page_key"], "")

    results.sort(
        key=lambda item: (
            _DECISION_ORDER[item["decision"]],
            -item["evidence_score"],
            item["pair_key"],
        )
    )
    return results if limit is None else results[: max(0, limit)]


def filename_candidate_pairs(
    page_keys: list[str] | set[str],
    threshold: float = 0.91,
    window: int = 32,
) -> list[tuple[str, str, float]]:
    """Recall similar filename pairs by normalized buckets and normalized neighborhoods."""
    records = []
    for page_key in sorted(set(page_keys)):
        normalized = normalize_name(page_key)
        if normalized:
            prefix = page_key.split("_", 1)[0].casefold() if "_" in page_key else ""
            records.append((page_key, prefix, normalized))

    pairs: dict[tuple[str, str], float] = {}
    exact_buckets: dict[tuple[str, str], list[str]] = defaultdict(list)
    for page_key, prefix, normalized in records:
        exact_buckets[(prefix, normalized)].append(page_key)
    for keys in exact_buckets.values():
        for left, right in combinations(keys, 2):
            pairs[tuple(sorted((left, right)))] = 1.0

    prefix_buckets: dict[tuple[str, str], list[tuple[str, str]]] = defaultdict(list)
    for page_key, prefix, normalized in records:
        prefix_buckets[(prefix, normalized[:2])].append((normalized, page_key))
    for values in prefix_buckets.values():
        ordered = sorted(values)
        for index, (left_norm, left_key) in enumerate(ordered):
            for right_norm, right_key in ordered[index + 1 : index + 1 + window]:
                longer = max(len(left_norm), len(right_norm))
                if abs(len(left_norm) - len(right_norm)) > max(3, int(longer * 0.25)):
                    continue
                ratio = SequenceMatcher(None, left_norm, right_norm).ratio()
                if ratio >= threshold:
                    pair = tuple(sorted((left_key, right_key)))
                    pairs[pair] = max(ratio, pairs.get(pair, 0.0))
    return [(left, right, ratio) for (left, right), ratio in sorted(pairs.items())]


def preflight_suggestion(suggestion: dict, wiki_dir: Path) -> dict:
    """Run the same semantic merge and schema validation used by execution."""
    checked = dict(suggestion)
    checked["preflight_errors"] = []
    if checked.get("decision") != "merge":
        checked["preflight_state"] = "not_applicable"
        return checked

    target_key = str(checked.get("left_page_key") or "")
    source_key = str(checked.get("right_page_key") or "")
    try:
        if not target_key or not source_key or target_key == source_key:
            raise ValueError("Merge preflight requires two distinct page keys.")
        if any(separator in target_key or separator in source_key for separator in ("/", "\\")):
            raise ValueError("Merge preflight page keys must be basenames.")
        target_path = (Path(wiki_dir).resolve() / f"{target_key}.md").resolve()
        source_path = (Path(wiki_dir).resolve() / f"{source_key}.md").resolve()
        if target_path.parent != Path(wiki_dir).resolve() or source_path.parent != Path(wiki_dir).resolve():
            raise ValueError("Merge preflight path escapes the wiki directory.")
        if not target_path.exists() or not source_path.exists():
            missing = [path.name for path in (target_path, source_path) if not path.exists()]
            raise FileNotFoundError("Missing wiki page(s): " + ", ".join(missing))

        from vector_lake.schema_validator import validate_schema
        from vector_lake.semantic_merge import merge_markdown_content
        from vector_lake.wiki_utils import split_frontmatter

        target_bytes = target_path.read_bytes()
        source_bytes = source_path.read_bytes()
        target_hash = hashlib.sha256(target_bytes).hexdigest()
        source_hash = hashlib.sha256(source_bytes).hexdigest()
        expected_target_hash = checked.get("left_projection_hash")
        expected_source_hash = checked.get("right_projection_hash")
        if expected_target_hash and expected_target_hash != target_hash:
            raise ValueError("Target Markdown projection changed before preflight.")
        if expected_source_hash and expected_source_hash != source_hash:
            raise ValueError("Source Markdown projection changed before preflight.")
        checked["left_projection_hash"] = target_hash
        checked["right_projection_hash"] = source_hash

        merged_content = merge_markdown_content(
            target_bytes.decode("utf-8"),
            source_bytes.decode("utf-8"),
            source_key=source_key,
        )
        frontmatter, body = split_frontmatter(merged_content)
        validate_schema(frontmatter, body, target_path.name)
        checked["preflight_state"] = "passed"
    except Exception as exc:
        checked["preflight_state"] = "blocked"
        checked["preflight_errors"] = [f"{type(exc).__name__}: {exc}"]
    return checked
