"""Deterministic duplicate-candidate analysis shared by governance and lint."""

from __future__ import annotations

import hashlib
import re
import unicodedata
from collections import defaultdict
from dataclasses import dataclass
from datetime import date
from difflib import SequenceMatcher
from itertools import combinations
from pathlib import Path
from typing import Iterable, Iterator, Mapping, TypeVar


_TYPE_PREFIX = re.compile(
    r"^(concept|vendor|institution|product|person|event|policy|standard|source|synthesis|system)[_-]+",
    re.IGNORECASE,
)
_REVISION_HASH_SUFFIX = re.compile(r"-([0-9a-f]{8})$", re.IGNORECASE)
_COMPACT_DATE_TOKEN = re.compile(r"(?<!\d)((?:19|20)\d{6})(?!\d)")
_SEPARATED_DATE_TOKEN = re.compile(
    r"(?<!\d)((?:19|20)\d{2})[-_.](\d{2})[-_.](\d{2})(?!\d)"
)
_ARXIV_ID = re.compile(r"^\d{4}\.\d{4,5}v\d+$", re.IGNORECASE)
_GENERIC_SOURCE_MARKERS = {
    "sourceautofixed",
    "sourceautogenerated",
    "sourcegenerated",
    "sourcestub",
    "sourcetemplate",
}
_DECISION_ORDER = {"merge": 0, "alias": 1, "review": 2, "keep_separate": 3}
_BUCKET_CLIQUE_LIMIT = 8
WikiBacklinkIndex = dict[str, tuple[tuple[str, str, str], ...]]
BucketValue = TypeVar("BucketValue", str, int)


@dataclass(frozen=True)
class FilenameCandidateEvent:
    """One classified filename-candidate edge or one suppressed edge."""

    left: str
    right: str
    ratio: float
    category: str
    eligible: bool
    detail: str = ""


@dataclass
class FilenameCandidateStats:
    """Exact counters for the streaming filename-candidate scan."""

    exact: int = 0
    hash_revision: int = 0
    ambiguous_revision: int = 0
    fuzzy: int = 0
    raw_source: int = 0
    temporal_series: int = 0
    numeric_identity_conflict: int = 0
    excluded_system_pages: int = 0

    def record(self, event: FilenameCandidateEvent) -> None:
        setattr(self, event.category, getattr(self, event.category) + 1)


def strip_entity_prefix(value: str) -> str:
    text = unicodedata.normalize("NFKC", str(value or "").strip())
    if text.casefold().endswith(".md"):
        text = text[:-3]
    return _TYPE_PREFIX.sub("", text, count=1)


def normalize_name(value: str) -> str:
    """Normalize identity text without discarding non-ASCII letters or digits."""
    text = unicodedata.normalize("NFKC", strip_entity_prefix(value)).casefold()
    return "".join(character for character in text if character.isalnum())


def normalize_page_key_identity(value: str) -> str:
    """Return a conservative identity key for case-insensitive Wiki references."""
    text = unicodedata.normalize("NFKC", str(value or "").strip())
    if text.casefold().endswith(".md"):
        text = text[:-3]
    return text.casefold()


def normalize_source_identity(value: str) -> str:
    """Normalize a durable source reference without collapsing path boundaries."""
    text = str(value or "").strip().replace("\\", "/")
    if text.startswith("[[") and text.endswith("]]" ):
        text = text[2:-2].split("|", 1)[0].strip()
    if text.startswith("MEMORY/"):
        text = text[len("MEMORY/") :]
    return text


def _page_key_type(value: str) -> str:
    text = unicodedata.normalize("NFKC", str(value or "").strip())
    if text.casefold().endswith(".md"):
        text = text[:-3]
    match = _TYPE_PREFIX.match(text)
    return match.group(1).casefold() if match else ""


def _effective_page_type(page_key: str, declared_type: str = "") -> str:
    prefix_type = _page_key_type(page_key)
    declared = str(declared_type or "").casefold()
    if "system" in {prefix_type, declared}:
        return "system"
    if declared and prefix_type and declared != prefix_type:
        return "type_conflict"
    return declared or prefix_type


def _valid_compact_date(value: str) -> bool:
    if not re.fullmatch(r"(?:19|20)\d{6}", value):
        return False
    try:
        date(int(value[:4]), int(value[4:6]), int(value[6:8]))
    except ValueError:
        return False
    return True


def _calendar_date_tokens(value: str) -> frozenset[str]:
    text = unicodedata.normalize("NFKC", str(value or ""))
    tokens = {
        match.group(1)
        for match in _COMPACT_DATE_TOKEN.finditer(text)
        if _valid_compact_date(match.group(1))
    }
    for match in _SEPARATED_DATE_TOKEN.finditer(text):
        compact = "".join(match.groups())
        if _valid_compact_date(compact):
            tokens.add(compact)
    return frozenset(tokens)


def _revision_hash_suffix(value: str) -> str:
    text = str(value or "").strip()
    if text.casefold().endswith(".md"):
        text = text[:-3]
    match = _REVISION_HASH_SUFFIX.search(text)
    if not match:
        return ""
    suffix = match.group(1)
    return "" if _valid_compact_date(suffix) else suffix.casefold()


def _ambiguous_revision_suffix(value: str) -> str:
    text = str(value or "").strip()
    if text.casefold().endswith(".md"):
        text = text[:-3]
    match = _REVISION_HASH_SUFFIX.search(text)
    if not match:
        return ""
    suffix = match.group(1)
    return suffix if _valid_compact_date(suffix) else ""


def _source_revision_base(page_key: str, entity_type: str = "source") -> str:
    if str(entity_type or "").casefold() != "source":
        return ""
    value = str(page_key or "").strip()
    if value.casefold().endswith(".md"):
        value = value[:-3]
    if _page_key_type(value) != "source" or not _revision_hash_suffix(value):
        return ""
    match = _REVISION_HASH_SUFFIX.search(value)
    return value[: match.start()] if match else ""


def _source_ambiguous_revision_base(
    page_key: str,
    entity_type: str = "source",
) -> str:
    if str(entity_type or "").casefold() != "source":
        return ""
    value = str(page_key or "").strip()
    if value.casefold().endswith(".md"):
        value = value[:-3]
    if _page_key_type(value) != "source" or not _ambiguous_revision_suffix(value):
        return ""
    match = _REVISION_HASH_SUFFIX.search(value)
    return value[: match.start()] if match else ""


def _source_revision_family_match(
    left_key: str,
    right_key: str,
    entity_type: str = "source",
) -> bool:
    left_base = _source_revision_base(left_key, entity_type)
    right_base = _source_revision_base(right_key, entity_type)
    if not left_base and not right_base:
        return False
    left_family = left_base or str(left_key)
    right_family = right_base or str(right_key)
    return normalize_page_key_identity(left_family) == normalize_page_key_identity(
        right_family
    )


def _unverified_non_source_hash_conflict(
    left_key: str,
    right_key: str,
    left_type: str,
    right_type: str,
) -> bool:
    if left_type != right_type or left_type in {"source", "system"}:
        return False

    def revision_like_base(page_key: str) -> str:
        value = str(page_key or "").strip()
        if value.casefold().endswith(".md"):
            value = value[:-3]
        suffix = _revision_hash_suffix(value)
        if not suffix:
            return ""
        return normalize_page_key_identity(value[: -(len(suffix) + 1)])

    left_base = revision_like_base(left_key)
    right_base = revision_like_base(right_key)
    left_identity = normalize_page_key_identity(left_key)
    right_identity = normalize_page_key_identity(right_key)
    return bool(
        (left_base and left_base == right_identity)
        or (right_base and right_base == left_identity)
        or (left_base and right_base and left_base == right_base)
    )


def _temporal_series_conflict(left_name: str, right_name: str) -> bool:
    left_dates = _calendar_date_tokens(left_name)
    right_dates = _calendar_date_tokens(right_name)
    return bool(left_dates and right_dates and left_dates != right_dates)


def _page_key_canonical_rank(page_key: str) -> tuple:
    entity_type = _page_key_type(page_key)
    is_revision = int(bool(_source_revision_base(page_key, entity_type)))
    normalized = normalize_name(page_key)
    return (
        is_revision,
        len(normalized),
        normalize_page_key_identity(page_key),
    )


def _bounded_bucket_pairs(
    values: Iterable[BucketValue],
    *,
    preferred_anchor: BucketValue | None = None,
    clique_limit: int = _BUCKET_CLIQUE_LIMIT,
) -> Iterator[tuple[BucketValue, BucketValue]]:
    """Return a clique for small buckets and a deterministic star for large ones."""
    ordered = sorted(set(values))
    if len(ordered) < 2:
        return
    if len(ordered) <= max(2, int(clique_limit)):
        yield from combinations(ordered, 2)
        return
    anchor = preferred_anchor if preferred_anchor in ordered else ordered[0]
    for value in ordered:
        if value != anchor:
            yield tuple(sorted((anchor, value)))


def build_wiki_backlink_index(wiki_dir: Path) -> WikiBacklinkIndex:
    """Scan Wiki links once and index normalized targets for batch preflight."""
    from vector_lake.wiki_utils import iter_markdown_files, iter_wiki_link_matches

    backlinks: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    for candidate_path in sorted(iter_markdown_files(wiki_dir), key=lambda path: path.name):
        candidate_bytes = candidate_path.read_bytes()
        candidate_content = candidate_bytes.decode("utf-8")
        projection_hash = hashlib.sha256(candidate_bytes).hexdigest()
        source_identity = normalize_page_key_identity(candidate_path.stem)
        target_identities = {
            normalize_page_key_identity(match.group(1))
            for match in iter_wiki_link_matches(candidate_content)
            if normalize_page_key_identity(match.group(1))
        }
        for target_identity in target_identities:
            backlinks[target_identity].append(
                (
                    source_identity,
                    candidate_path.stem,
                    projection_hash,
                )
            )
    return {
        target_identity: tuple(entries)
        for target_identity, entries in backlinks.items()
    }


def source_identity_candidate_pairs(
    page_sources: dict[str, object],
) -> list[tuple[str, str, str]]:
    """Return page pairs that name the same concrete raw artifact."""
    buckets: dict[str, list[str]] = defaultdict(list)
    for page_key, values in page_sources.items():
        for value in _string_list(values):
            identity = normalize_source_identity(value)
            if identity.startswith("raw/"):
                buckets[identity].append(str(page_key))

    pairs = []
    for identity, page_keys in buckets.items():
        unique_keys = sorted(set(page_keys))
        anchor = min(unique_keys, key=_page_key_canonical_rank)
        for left, right in _bounded_bucket_pairs(
            unique_keys,
            preferred_anchor=anchor,
        ):
            pairs.append((left, right, identity))
    return sorted(pairs)


def _string_list(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, (str, int, float)):
        value = [value]
    if not isinstance(value, (list, tuple, set, frozenset)):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def _tokens(value: str) -> frozenset[str]:
    text = unicodedata.normalize("NFKC", strip_entity_prefix(value)).casefold()
    return frozenset(token for token in re.findall(r"[^\W_]+", text, re.UNICODE) if token)


def _stable_sources(entity: dict) -> frozenset[str]:
    values = [
        *_string_list(entity.get("sources")),
        *_string_list(entity.get("source_ids")),
    ]
    stable = set()
    for source in values:
        normalized = normalize_name(source)
        if not normalized:
            continue
        if normalized in _GENERIC_SOURCE_MARKERS:
            continue
        if any(marker in normalized for marker in ("autofixed", "autogenerated", "template", "stub")):
            continue
        stable.add(normalized)
    return frozenset(stable)


def _body_text(entity: dict) -> str:
    for field in ("raw_text", "body", "summary", "description"):
        value = entity.get(field)
        if isinstance(value, str) and value.strip():
            return re.sub(r"\s+", " ", value).strip().casefold()
    return ""


def _body_fingerprint(body: str) -> str:
    if len(body) < 40:
        return ""
    normalized = re.sub(r"\s+", " ", body).strip()
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def _record(entity: dict) -> dict:
    canonical_name = str(
        entity.get("canonical_name")
        or entity.get("title")
        or entity.get("page_key")
        or entity.get("entity_id")
        or ""
    )
    aliases = _string_list(entity.get("aliases"))
    page_key = str(entity.get("page_key") or "")
    declared_type = str(entity.get("type") or entity.get("entity_type") or "")
    effective_type = _effective_page_type(page_key, declared_type)
    variants = [canonical_name, strip_entity_prefix(page_key), *aliases]
    norms = frozenset(filter(None, (normalize_name(value) for value in variants)))
    alias_norms = frozenset(filter(None, (normalize_name(value) for value in aliases)))
    body = _body_text(entity)
    return {
        "entity": entity,
        "entity_id": str(entity.get("entity_id") or page_key or canonical_name),
        "name": canonical_name,
        "page_key": page_key,
        "effective_type": effective_type,
        "primary_norm": normalize_name(canonical_name),
        "norms": norms,
        "alias_norms": alias_norms,
        "tokens": frozenset(token for value in variants for token in _tokens(value)),
        "sources": _stable_sources(entity),
        "source_identities": frozenset(
            identity
            for value in [
                *_string_list(entity.get("sources")),
                *_string_list(entity.get("source_ids")),
            ]
            for identity in [normalize_source_identity(value)]
            if identity.startswith("raw/")
        ),
        "body": body,
        "body_fingerprint": _body_fingerprint(body),
    }


def _name_similarity(left: dict, right: dict) -> float:
    if not left["primary_norm"] or not right["primary_norm"]:
        return 0.0
    if left["primary_norm"] == right["primary_norm"]:
        return 1.0
    return SequenceMatcher(None, left["primary_norm"], right["primary_norm"]).ratio()


def _numeric_identity_conflict(left: dict, right: dict) -> bool:
    return _numeric_identity_conflict_values(
        left["name"],
        right["name"],
    ) or _numeric_identity_conflict_values(
        left["page_key"],
        right["page_key"],
    )


def _temporal_identity_conflict(left: dict, right: dict) -> bool:
    return _temporal_series_conflict(
        left["name"],
        right["name"],
    ) or _temporal_series_conflict(
        left["page_key"],
        right["page_key"],
    )


def _numeric_identity_tokens(value: str) -> tuple[str, ...]:
    """Keep numeric group boundaries while normalizing valid calendar dates."""
    text = unicodedata.normalize("NFKC", strip_entity_prefix(value)).casefold()
    date_spans: list[tuple[int, int, str]] = []
    for match in _SEPARATED_DATE_TOKEN.finditer(text):
        compact = "".join(match.groups())
        if _valid_compact_date(compact):
            date_spans.append((match.start(), match.end(), compact))
    for match in _COMPACT_DATE_TOKEN.finditer(text):
        compact = match.group(1)
        if _valid_compact_date(compact):
            date_spans.append((match.start(), match.end(), compact))

    tokens: list[str] = []
    cursor = 0
    for start, end, compact in sorted(date_spans):
        if start < cursor:
            continue
        tokens.extend(
            f"num:{number}"
            for number in re.findall(r"\d+", text[cursor:start])
        )
        tokens.append(f"date:{compact}")
        cursor = end
    tokens.extend(
        f"num:{number}"
        for number in re.findall(r"\d+", text[cursor:])
    )
    return tuple(tokens)


def _numeric_identity_conflict_values(left_name: str, right_name: str) -> bool:
    left_norm = normalize_name(left_name)
    right_norm = normalize_name(right_name)
    left_numbers = _numeric_identity_tokens(left_name)
    right_numbers = _numeric_identity_tokens(right_name)
    if left_numbers == right_numbers:
        return False
    left_surface = unicodedata.normalize(
        "NFKC",
        strip_entity_prefix(left_name),
    ).casefold()
    right_surface = unicodedata.normalize(
        "NFKC",
        strip_entity_prefix(right_name),
    ).casefold()
    if _ARXIV_ID.fullmatch(left_surface) and _ARXIV_ID.fullmatch(right_surface):
        return True
    left_lead = re.match(r"^[^\d]+", left_surface)
    right_lead = re.match(r"^[^\d]+", right_surface)
    if left_lead and right_lead:
        left_prefix = re.sub(r"\W+", "", left_lead.group(0))
        right_prefix = re.sub(r"\W+", "", right_lead.group(0))
        if left_prefix and left_prefix == right_prefix:
            return True
    left_base = re.sub(r"\d+", "", left_norm)
    right_base = re.sub(r"\d+", "", right_norm)
    return bool(
        left_base
        and (
            left_base == right_base
            or left_base.startswith(right_base)
            or right_base.startswith(left_base)
        )
    )


def _numeric_identity_signature(value: str) -> tuple[str, ...]:
    """Preserve version/date identity while ignoring punctuation variants."""
    return _numeric_identity_tokens(value)


def _plural_equivalent(left_norm: str, right_norm: str) -> bool:
    if not left_norm or not right_norm:
        return False

    def singular(value: str) -> str:
        return value[:-1] if value.endswith("s") and not value.endswith("ss") else value

    return left_norm != right_norm and singular(left_norm) == singular(right_norm)


def _canonical_rank(record: dict) -> tuple:
    entity = record["entity"]
    entity_type = record["effective_type"]
    categories = {str(item).casefold() for item in _string_list(entity.get("categories"))}
    is_backlog_source = entity_type == "source" and (
        str(entity.get("topic_cluster") or "").casefold() == "raw_ingest_backlog"
        or "raw_ingest_backlog" in categories
        or "historical awaiting_subagent backlog" in record["body"]
    )
    stable_source_identity = int(
        entity_type != "source"
        or not _source_revision_base(str(record["page_key"] or ""), entity_type)
    )
    curated_source = int(entity_type != "source" or not is_backlog_source)
    status = str(entity.get("status", "")).casefold()
    status_score = 3 if status == "active" else 2 if status == "draft" else 0
    page_key_score = int(bool(record["page_key"]) and "/" not in record["page_key"] and "\\" not in record["page_key"])
    body = record["body"]
    non_stub_body = int(bool(body) and "auto-generated stub" not in body and len(body) >= 80)
    source_score = min(len(record["sources"]), 5)
    inbound_score = int(entity.get("inbound_count") or entity.get("inlinks") or 0)
    return (
        curated_source,
        stable_source_identity,
        status_score,
        page_key_score,
        non_stub_body,
        source_score,
        inbound_score,
        len(body),
    )


def _canonical_record_index(records: list[dict], indices: Iterable[int]) -> int:
    """Select the same stable target that component materialization will keep."""
    ordered = sorted(
        set(indices),
        key=lambda index: records[index]["entity_id"],
    )
    return max(ordered, key=lambda index: _canonical_rank(records[index]))


def _evaluate_pair(left: dict, right: dict) -> dict:
    primary_exact = bool(left["primary_norm"]) and left["primary_norm"] == right["primary_norm"]
    normalized_overlap = left["norms"] & right["norms"]
    alias_overlap = left["alias_norms"] & right["alias_norms"]
    stable_source_overlap = left["sources"] & right["sources"]
    raw_identity_overlap = left["source_identities"] & right["source_identities"]
    token_overlap = left["tokens"] & right["tokens"]
    similarity = _name_similarity(left, right)
    body_similarity = 0.0
    if (
        similarity >= 0.90
        and len(left["body"]) >= 40
        and len(right["body"]) >= 40
    ):
        body_similarity = SequenceMatcher(
            None,
            left["body"][:2000],
            right["body"][:2000],
        ).quick_ratio()
    content_fingerprint_match = bool(
        left["body_fingerprint"]
        and left["body_fingerprint"] == right["body_fingerprint"]
    )
    left_type = left["effective_type"]
    right_type = right["effective_type"]
    left_revision_base = _source_revision_base(left["page_key"], left_type)
    right_revision_base = _source_revision_base(right["page_key"], right_type)
    revision_suffix_match = bool(
        left_type == right_type == "source"
        and left["page_key"]
        and right["page_key"]
        and left["page_key"] != right["page_key"]
        and (
            (
                left_revision_base
                and normalize_page_key_identity(left_revision_base)
                == normalize_page_key_identity(right["page_key"])
            )
            or (
                right_revision_base
                and normalize_page_key_identity(right_revision_base)
                == normalize_page_key_identity(left["page_key"])
            )
            or (
                left_revision_base
                and right_revision_base
                and normalize_page_key_identity(left_revision_base)
                == normalize_page_key_identity(right_revision_base)
            )
        )
    )
    left_ambiguous_base = _source_ambiguous_revision_base(
        left["page_key"],
        left_type,
    )
    right_ambiguous_base = _source_ambiguous_revision_base(
        right["page_key"],
        right_type,
    )
    ambiguous_revision_match = bool(
        left_type == right_type == "source"
        and left["page_key"]
        and right["page_key"]
        and left["page_key"] != right["page_key"]
        and (
            (
                left_ambiguous_base
                and normalize_page_key_identity(left_ambiguous_base)
                == normalize_page_key_identity(right["page_key"])
            )
            or (
                right_ambiguous_base
                and normalize_page_key_identity(right_ambiguous_base)
                == normalize_page_key_identity(left["page_key"])
            )
        )
    )
    temporal_conflict = _temporal_identity_conflict(left, right)
    numeric_conflict = _numeric_identity_conflict(left, right)
    plural_equivalent = _plural_equivalent(left["primary_norm"], right["primary_norm"])
    surface_type_conflict = "type_conflict" in {left_type, right_type}
    type_conflict = bool(left_type and right_type and left_type != right_type)
    both_sources = left_type == right_type == "source"
    non_source_hash_conflict = _unverified_non_source_hash_conflict(
        left["page_key"],
        right["page_key"],
        left_type,
        right_type,
    )

    reasons = []
    evidence_score = round(similarity * 45)
    if primary_exact:
        reasons.append("normalized-name-match")
        evidence_score += 45
    elif normalized_overlap:
        reasons.append("normalized-variant-match")
        evidence_score += 30
    if alias_overlap:
        reasons.append("alias-overlap:" + ", ".join(sorted(alias_overlap)[:3]))
        evidence_score += 15
    if plural_equivalent:
        reasons.append("singular-plural-equivalent")
        evidence_score += 10
    if stable_source_overlap:
        reasons.append("stable-source-overlap")
        evidence_score += min(15, 5 * len(stable_source_overlap))
    if raw_identity_overlap:
        reasons.append("exact-raw-identity:" + ", ".join(sorted(raw_identity_overlap)[:2]))
        evidence_score += 25
    if content_fingerprint_match:
        reasons.append("content-fingerprint-match")
        evidence_score += 20
    if revision_suffix_match:
        reasons.append("revision-suffix-match")
        evidence_score += 20
    if ambiguous_revision_match:
        reasons.append("ambiguous-date-shaped-revision")
    if body_similarity >= 0.55:
        reasons.append(f"body-similarity:{body_similarity:.0%}")
        evidence_score += round(body_similarity * 10)
    if len(token_overlap) >= 2:
        reasons.append("token-overlap:" + ", ".join(sorted(token_overlap)[:4]))
        evidence_score += 5

    left_entity = left["entity"]
    right_entity = right["entity"]
    left_domain = str(left_entity.get("domain") or "")
    right_domain = str(right_entity.get("domain") or "")
    left_cluster = str(left_entity.get("topic_cluster") or "")
    right_cluster = str(right_entity.get("topic_cluster") or "")
    if (
        left_domain
        and left_cluster
        and left_domain.casefold() != "general"
        and left_domain == right_domain
        and left_cluster == right_cluster
    ):
        reasons.append("domain-cluster-match")
        evidence_score += 5

    if type_conflict or surface_type_conflict:
        reasons.append("entity-type-conflict")
    if temporal_conflict:
        reasons.append("temporal-series-conflict")
    if non_source_hash_conflict:
        reasons.append("unverified-non-source-hash-suffix")

    source_identity_evidence = bool(
        raw_identity_overlap
        or content_fingerprint_match
        or revision_suffix_match
        or body_similarity >= 0.90
    )

    if surface_type_conflict:
        decision = "keep_separate"
        evidence_score = min(evidence_score, 25)
    elif type_conflict and "source" in {left_type, right_type}:
        decision = "keep_separate"
        evidence_score = min(evidence_score, 25)
    elif both_sources and not raw_identity_overlap:
        if left["source_identities"] and right["source_identities"]:
            reasons.append("source-raw-identity-mismatch")
        else:
            reasons.append("source-raw-identity-missing")
        decision = "review"
        evidence_score = min(evidence_score, 70)
    elif both_sources and raw_identity_overlap:
        decision = "merge"
    elif revision_suffix_match and left_type == right_type:
        decision = "merge"
    elif non_source_hash_conflict:
        decision = "keep_separate"
        evidence_score = min(evidence_score, 35)
    elif temporal_conflict:
        decision = "keep_separate"
        evidence_score = min(evidence_score, 35)
    elif numeric_conflict:
        reasons.append("numeric-identity-conflict")
        decision = "keep_separate"
        evidence_score = min(evidence_score, 35)
    elif type_conflict:
        decision = "review"
        evidence_score = min(evidence_score, 60)
    elif primary_exact and left_type == "source" and not source_identity_evidence:
        reasons.append("source-identity-evidence-missing")
        decision = "review"
        evidence_score = min(evidence_score, 70)
    elif primary_exact:
        decision = "merge"
    elif plural_equivalent and (stable_source_overlap or body_similarity >= 0.55):
        decision = "merge"
    elif similarity >= 0.96 and (
        stable_source_overlap
        or (body_similarity >= 0.80 and len(token_overlap) >= 2)
    ):
        decision = "merge"
    elif similarity >= 0.94:
        decision = "alias"
    elif alias_overlap or similarity >= 0.84:
        decision = "review"
    else:
        decision = "keep_separate"

    pair_key = "::".join(sorted((left["entity_id"], right["entity_id"])))
    return {
        "pair_key": pair_key,
        "evidence_score": min(100, max(0, evidence_score)),
        "score": min(100, max(0, evidence_score)),
        "decision": decision,
        "left_entity_id": left["entity_id"],
        "left_name": left["name"],
        "left_page_key": left["page_key"],
        "right_entity_id": right["entity_id"],
        "right_name": right["name"],
        "right_page_key": right["page_key"],
        "name_similarity": round(similarity, 4),
        "body_similarity": round(body_similarity, 4),
        "reasons": reasons,
        "domain": left_domain or right_domain or "General",
        "preflight_state": "not_run",
        "preflight_errors": [],
    }


class _UnionFind:
    def __init__(self, values):
        self.parent = {value: value for value in values}

    def find(self, value):
        parent = self.parent[value]
        if parent != value:
            self.parent[value] = self.find(parent)
        return self.parent[value]

    def union(self, left, right):
        left_root = self.find(left)
        right_root = self.find(right)
        if left_root != right_root:
            self.parent[right_root] = left_root


def _candidate_index_pairs(
    records: list[dict],
    fuzzy_threshold: float = 0.82,
    window: int = 16,
) -> set[tuple[int, int]]:
    pairs: set[tuple[int, int]] = set()
    norm_buckets: dict[tuple[str, str, tuple[str, ...]], list[int]] = defaultdict(
        list
    )
    norm_type_representatives: dict[str, dict[str, list[int]]] = defaultdict(
        lambda: defaultdict(list)
    )
    for index, record in enumerate(records):
        entity_type = record["effective_type"]
        identity_signature = _numeric_identity_signature(record["page_key"])
        for norm in record["norms"]:
            if norm:
                norm_buckets[(entity_type, norm, identity_signature)].append(index)
                norm_type_representatives[norm][entity_type].append(index)
    for indices in norm_buckets.values():
        unique = sorted(set(indices))
        anchor = _canonical_record_index(records, unique)
        pairs.update(
            _bounded_bucket_pairs(unique, preferred_anchor=anchor)
        )
    for type_buckets in norm_type_representatives.values():
        if len(type_buckets) < 2:
            continue
        representatives = [
            _canonical_record_index(records, indices)
            for indices in type_buckets.values()
        ]
        pairs.update(_bounded_bucket_pairs(representatives))

    revision_buckets: dict[tuple[str, str], list[int]] = defaultdict(list)
    ambiguous_revision_buckets: dict[tuple[str, str], list[int]] = defaultdict(
        list
    )
    source_identity_buckets: dict[str, list[int]] = defaultdict(list)
    page_key_indices: dict[tuple[str, str], list[int]] = defaultdict(list)
    for index, record in enumerate(records):
        entity_type = record["effective_type"]
        page_key_indices[
            (entity_type, normalize_page_key_identity(record["page_key"]))
        ].append(index)
    for index, record in enumerate(records):
        entity_type = record["effective_type"]
        page_key = str(record["page_key"] or "")
        revision_base = _source_revision_base(page_key, entity_type)
        ambiguous_base = _source_ambiguous_revision_base(page_key, entity_type)
        if revision_base:
            revision_buckets[
                (entity_type, normalize_page_key_identity(revision_base))
            ].append(index)
        elif ambiguous_base:
            ambiguous_revision_buckets[
                (entity_type, normalize_page_key_identity(ambiguous_base))
            ].append(index)
        if entity_type == "source":
            for identity in record["source_identities"]:
                source_identity_buckets[identity].append(index)
    for (entity_type, base_identity), revision_indices in revision_buckets.items():
        canonical_indices = page_key_indices.get((entity_type, base_identity), [])
        if not canonical_indices:
            unique = sorted(set(revision_indices))
            anchor = _canonical_record_index(records, unique)
            pairs.update(
                _bounded_bucket_pairs(unique, preferred_anchor=anchor)
            )
            continue
        anchor = _canonical_record_index(records, canonical_indices)
        for revision_index in sorted(set(revision_indices)):
            if revision_index != anchor:
                pairs.add(tuple(sorted((anchor, revision_index))))
    for (entity_type, base_identity), revision_indices in (
        ambiguous_revision_buckets.items()
    ):
        canonical_indices = page_key_indices.get((entity_type, base_identity), [])
        if not canonical_indices:
            continue
        anchor = _canonical_record_index(records, canonical_indices)
        for revision_index in sorted(set(revision_indices)):
            if revision_index != anchor:
                pairs.add(tuple(sorted((anchor, revision_index))))
    for indices in source_identity_buckets.values():
        unique = sorted(set(indices))
        anchor = _canonical_record_index(records, unique)
        pairs.update(
            _bounded_bucket_pairs(unique, preferred_anchor=anchor)
        )

    type_buckets: dict[tuple[str, str], list[int]] = defaultdict(list)
    for index, record in enumerate(records):
        entity_type = record["effective_type"]
        type_buckets[
            (entity_type, record["primary_norm"][:2])
        ].append(index)
    for indices in type_buckets.values():
        ordered = sorted(indices, key=lambda index: (records[index]["primary_norm"], records[index]["entity_id"]))
        for position, left_index in enumerate(ordered):
            left_norm = records[left_index]["primary_norm"]
            if not left_norm:
                continue
            for right_index in ordered[position + 1 : position + 1 + window]:
                right_norm = records[right_index]["primary_norm"]
                if not right_norm:
                    continue
                longer = max(len(left_norm), len(right_norm))
                if abs(len(left_norm) - len(right_norm)) > max(3, int(longer * 0.25)):
                    continue
                pair = tuple(sorted((left_index, right_index)))
                if pair in pairs:
                    continue
                if _temporal_identity_conflict(
                    records[left_index],
                    records[right_index],
                ) or _numeric_identity_conflict(
                    records[left_index],
                    records[right_index],
                ):
                    continue
                similarity = SequenceMatcher(None, left_norm, right_norm).ratio()
                if similarity >= fuzzy_threshold:
                    pairs.add(pair)
    return pairs


def analyze_entities(
    entities: list[dict],
    limit: int | None = 20,
    versions: dict[str, str] | None = None,
) -> list[dict]:
    """Return component-aware candidates with explicit merge/alias/review/keep decisions."""
    records = []
    for entity in entities:
        if str(entity.get("status", "")).casefold() == "merged":
            continue
        declared_type = str(
            entity.get("type") or entity.get("entity_type") or ""
        )
        if _effective_page_type(
            str(entity.get("page_key") or ""),
            declared_type,
        ) == "system":
            continue
        record = _record(entity)
        if record["primary_norm"]:
            records.append(record)

    record_by_id = {record["entity_id"]: record for record in records}
    evaluated = [
        _evaluate_pair(records[left_index], records[right_index])
        for left_index, right_index in sorted(_candidate_index_pairs(records))
        if records[left_index]["entity_id"] != records[right_index]["entity_id"]
    ]

    union_find = _UnionFind(record_by_id)
    for candidate in evaluated:
        if candidate["decision"] == "merge":
            union_find.union(candidate["left_entity_id"], candidate["right_entity_id"])

    components: dict[str, list[str]] = defaultdict(list)
    for entity_id in record_by_id:
        components[union_find.find(entity_id)].append(entity_id)

    merge_results = []
    merged_component_by_id = {}
    component_target_by_id = {}
    evaluated_by_pair = {candidate["pair_key"]: candidate for candidate in evaluated}
    for member_ids in components.values():
        if len(member_ids) < 2:
            continue
        ordered_members = sorted(member_ids)
        component_id = "merge_" + hashlib.sha1("::".join(ordered_members).encode("utf-8")).hexdigest()[:12]
        target_id = max(ordered_members, key=lambda entity_id: _canonical_rank(record_by_id[entity_id]))
        for entity_id in ordered_members:
            merged_component_by_id[entity_id] = component_id
            component_target_by_id[entity_id] = target_id
        for source_id in ordered_members:
            if source_id == target_id:
                continue
            pair_key = "::".join(sorted((target_id, source_id)))
            candidate = dict(
                evaluated_by_pair.get(pair_key)
                or _evaluate_pair(record_by_id[target_id], record_by_id[source_id])
            )
            candidate.update(
                {
                    "left_entity_id": target_id,
                    "left_name": record_by_id[target_id]["name"],
                    "left_page_key": record_by_id[target_id]["page_key"],
                    "right_entity_id": source_id,
                    "right_name": record_by_id[source_id]["name"],
                    "right_page_key": record_by_id[source_id]["page_key"],
                    "decision": "review" if len(ordered_members) > 2 else "merge",
                    "component_id": component_id,
                    "component_size": len(ordered_members),
                }
            )
            if len(ordered_members) > 2 and "large-component-review" not in candidate["reasons"]:
                candidate["reasons"] = [*candidate["reasons"], "large-component-review"]
            merge_results.append(candidate)

    other_results_by_pair = {}
    for candidate in evaluated:
        left_component = merged_component_by_id.get(candidate["left_entity_id"])
        right_component = merged_component_by_id.get(candidate["right_entity_id"])
        if left_component and left_component == right_component:
            continue
        original_decision = candidate["decision"]
        left_id = component_target_by_id.get(
            candidate["left_entity_id"],
            candidate["left_entity_id"],
        )
        right_id = component_target_by_id.get(
            candidate["right_entity_id"],
            candidate["right_entity_id"],
        )
        if left_id == right_id:
            continue
        remapped = (
            left_id != candidate["left_entity_id"]
            or right_id != candidate["right_entity_id"]
        )
        if remapped:
            ordered_ids = sorted((left_id, right_id))
            candidate = _evaluate_pair(
                record_by_id[ordered_ids[0]],
                record_by_id[ordered_ids[1]],
            )
            if _DECISION_ORDER[candidate["decision"]] < _DECISION_ORDER[
                original_decision
            ]:
                candidate["decision"] = original_decision
            if "component-endpoint-remap" not in candidate["reasons"]:
                candidate["reasons"] = [
                    *candidate["reasons"],
                    "component-endpoint-remap",
                ]
        else:
            candidate = dict(candidate)
        candidate["component_id"] = ""
        candidate["component_size"] = 1
        existing = other_results_by_pair.get(candidate["pair_key"])
        if existing is None or (
            _DECISION_ORDER[candidate["decision"]],
            candidate["evidence_score"],
        ) > (
            _DECISION_ORDER[existing["decision"]],
            existing["evidence_score"],
        ):
            other_results_by_pair[candidate["pair_key"]] = candidate

    other_results = list(other_results_by_pair.values())

    versions = versions or {}
    results = merge_results + other_results
    for candidate in results:
        candidate["left_version"] = versions.get(candidate["left_page_key"], "")
        candidate["right_version"] = versions.get(candidate["right_page_key"], "")

    results.sort(
        key=lambda item: (
            _DECISION_ORDER[item["decision"]],
            -item["evidence_score"],
            item["pair_key"],
        )
    )
    return results if limit is None else results[: max(0, limit)]


def iter_filename_candidates(
    page_keys: Iterable[str],
    *,
    page_types: Mapping[str, str] | None = None,
    page_sources: Mapping[str, object] | None = None,
    threshold: float = 0.91,
    window: int = 32,
    stats: FilenameCandidateStats | None = None,
) -> Iterator[FilenameCandidateEvent]:
    """Stream typed candidate edges and suppressed numeric/temporal edges."""
    stats = stats if stats is not None else FilenameCandidateStats()
    declared_types = page_types or {}
    source_values = page_sources or {}
    records: list[tuple[str, str, str]] = []
    for page_key in sorted(set(map(str, page_keys))):
        entity_type = _effective_page_type(
            page_key,
            declared_types.get(page_key, ""),
        )
        if entity_type == "system":
            stats.excluded_system_pages += 1
            continue
        normalized = normalize_name(page_key)
        if normalized:
            records.append((page_key, entity_type, normalized))

    key_buckets: dict[str, list[str]] = defaultdict(list)
    for page_key, _entity_type, _normalized in records:
        key_buckets[normalize_page_key_identity(page_key)].append(page_key)
    key_lookup = {
        identity: min(keys, key=_page_key_canonical_rank)
        for identity, keys in key_buckets.items()
    }
    page_raw_ids: dict[str, frozenset[str]] = {}
    raw_buckets: dict[str, list[str]] = defaultdict(list)
    for page_key, entity_type, _normalized in records:
        identities = frozenset(
            identity
            for value in _string_list(source_values.get(page_key))
            for identity in [normalize_source_identity(value)]
            if entity_type == "source" and identity.startswith("raw/")
        )
        page_raw_ids[page_key] = identities
        for identity in identities:
            raw_buckets[identity].append(page_key)

    def shared_raw(left: str, right: str) -> bool:
        return bool(page_raw_ids.get(left, frozenset()) & page_raw_ids.get(right, frozenset()))

    raw_emitted: set[tuple[str, str]] = set()
    for identity in sorted(raw_buckets):
        keys = sorted(set(raw_buckets[identity]))
        anchor = min(keys, key=_page_key_canonical_rank)
        for left, right in _bounded_bucket_pairs(keys, preferred_anchor=anchor):
            pair = tuple(sorted((left, right)))
            if pair in raw_emitted:
                continue
            raw_emitted.add(pair)
            event = FilenameCandidateEvent(
                pair[0],
                pair[1],
                1.0,
                "raw_source",
                True,
                identity,
            )
            stats.record(event)
            yield event

    exact_buckets: dict[tuple[str, str, tuple[str, ...]], list[str]] = defaultdict(
        list
    )
    for page_key, entity_type, normalized in records:
        exact_buckets[
            (entity_type, normalized, _numeric_identity_signature(page_key))
        ].append(page_key)
    for bucket_key in sorted(exact_buckets):
        keys = sorted(set(exact_buckets[bucket_key]))
        anchor = min(keys, key=_page_key_canonical_rank)
        for left, right in _bounded_bucket_pairs(keys, preferred_anchor=anchor):
            if shared_raw(left, right):
                continue
            event = FilenameCandidateEvent(
                left,
                right,
                1.0,
                "exact",
                True,
            )
            stats.record(event)
            yield event

    for category, base_function in (
        ("hash_revision", _source_revision_base),
        ("ambiguous_revision", _source_ambiguous_revision_base),
    ):
        revision_buckets: dict[str, list[str]] = defaultdict(list)
        for page_key, entity_type, _normalized in records:
            base = base_function(page_key, entity_type)
            if base:
                revision_buckets[normalize_page_key_identity(base)].append(page_key)
        for base_identity in sorted(revision_buckets):
            revisions = sorted(set(revision_buckets[base_identity]))
            canonical = key_lookup.get(base_identity)
            if canonical:
                candidate_pairs = (
                    tuple(sorted((canonical, revision)))
                    for revision in revisions
                )
            elif category == "hash_revision":
                anchor = min(revisions, key=_page_key_canonical_rank)
                candidate_pairs = _bounded_bucket_pairs(
                    revisions,
                    preferred_anchor=anchor,
                )
            else:
                continue
            for left, right in candidate_pairs:
                if shared_raw(left, right):
                    continue
                event = FilenameCandidateEvent(
                    left,
                    right,
                    1.0,
                    category,
                    True,
                    base_identity,
                )
                stats.record(event)
                yield event

    prefix_buckets: dict[tuple[str, str], list[tuple[str, str]]] = defaultdict(list)
    for page_key, entity_type, normalized in records:
        prefix_buckets[(entity_type, normalized[:2])].append(
            (normalized, page_key)
        )
    for bucket_key in sorted(prefix_buckets):
        ordered = sorted(prefix_buckets[bucket_key])
        for index, (left_norm, left_key) in enumerate(ordered):
            for right_norm, right_key in ordered[index + 1 : index + 1 + window]:
                if (
                    left_norm == right_norm
                    and _numeric_identity_signature(left_key)
                    == _numeric_identity_signature(right_key)
                ):
                    continue
                entity_type = bucket_key[0]
                if _source_revision_family_match(
                    left_key,
                    right_key,
                    entity_type,
                ):
                    continue
                left_ambiguous = _source_ambiguous_revision_base(
                    left_key,
                    entity_type,
                )
                right_ambiguous = _source_ambiguous_revision_base(
                    right_key,
                    entity_type,
                )
                if (
                    left_ambiguous
                    and normalize_page_key_identity(left_ambiguous)
                    == normalize_page_key_identity(right_key)
                ) or (
                    right_ambiguous
                    and normalize_page_key_identity(right_ambiguous)
                    == normalize_page_key_identity(left_key)
                ):
                    continue
                longer = max(len(left_norm), len(right_norm))
                if abs(len(left_norm) - len(right_norm)) > max(
                    3,
                    int(longer * 0.25),
                ):
                    continue
                ratio = SequenceMatcher(None, left_norm, right_norm).ratio()
                if ratio < threshold or shared_raw(left_key, right_key):
                    continue
                if _temporal_series_conflict(left_key, right_key):
                    category = "temporal_series"
                    eligible = False
                elif _numeric_identity_conflict_values(left_key, right_key):
                    category = "numeric_identity_conflict"
                    eligible = False
                else:
                    category = "fuzzy"
                    eligible = True
                left, right = sorted((left_key, right_key))
                event = FilenameCandidateEvent(
                    left,
                    right,
                    ratio,
                    category,
                    eligible,
                )
                stats.record(event)
                yield event


def filename_candidate_pairs(
    page_keys: list[str] | set[str],
    threshold: float = 0.91,
    window: int = 32,
) -> list[tuple[str, str, float]]:
    """Return stable actionable filename pairs for compatibility callers."""
    return [
        (event.left, event.right, event.ratio)
        for event in iter_filename_candidates(
            page_keys,
            threshold=threshold,
            window=window,
        )
        if event.eligible
    ]


def preflight_suggestion(
    suggestion: dict,
    wiki_dir: Path,
    backlink_index: WikiBacklinkIndex | None = None,
) -> dict:
    """Run the same semantic merge and schema validation used by execution."""
    checked = dict(suggestion)
    checked["preflight_errors"] = []
    if checked.get("decision") != "merge":
        checked["preflight_state"] = "not_applicable"
        return checked

    target_key = str(checked.get("left_page_key") or "")
    source_key = str(checked.get("right_page_key") or "")
    try:
        if (
            not target_key
            or not source_key
            or normalize_page_key_identity(target_key)
            == normalize_page_key_identity(source_key)
        ):
            raise ValueError("Merge preflight requires two distinct page keys.")
        if any(separator in target_key or separator in source_key for separator in ("/", "\\")):
            raise ValueError("Merge preflight page keys must be basenames.")
        from vector_lake.wiki_utils import iter_markdown_files

        wiki_root = Path(wiki_dir).resolve()
        wiki_paths = {
            path.stem: path.resolve()
            for path in iter_markdown_files(wiki_root)
        }
        target_path = wiki_paths.get(target_key, wiki_root / f"{target_key}.md")
        source_path = wiki_paths.get(source_key, wiki_root / f"{source_key}.md")
        if target_path.parent != wiki_root or source_path.parent != wiki_root:
            raise ValueError("Merge preflight path escapes the wiki directory.")
        if target_path == source_path:
            raise ValueError("Merge preflight requires two distinct physical pages.")
        if not target_path.exists() or not source_path.exists():
            missing = [path.name for path in (target_path, source_path) if not path.exists()]
            raise FileNotFoundError("Missing wiki page(s): " + ", ".join(missing))

        from vector_lake.schema_validator import validate_schema
        from vector_lake.semantic_merge import merge_markdown_content
        from vector_lake.wiki_utils import get_memory_dir, split_frontmatter

        target_bytes = target_path.read_bytes()
        source_bytes = source_path.read_bytes()
        target_hash = hashlib.sha256(target_bytes).hexdigest()
        source_hash = hashlib.sha256(source_bytes).hexdigest()
        expected_target_hash = checked.get("left_projection_hash")
        expected_source_hash = checked.get("right_projection_hash")
        if expected_target_hash and expected_target_hash != target_hash:
            raise ValueError("Target Markdown projection changed before preflight.")
        if expected_source_hash and expected_source_hash != source_hash:
            raise ValueError("Source Markdown projection changed before preflight.")
        checked["left_projection_hash"] = target_hash
        checked["right_projection_hash"] = source_hash

        target_frontmatter, _target_body = split_frontmatter(target_bytes.decode("utf-8"))
        source_frontmatter, _source_body = split_frontmatter(source_bytes.decode("utf-8"))
        if (
            str(target_frontmatter.get("type") or "").casefold() == "source"
            and str(source_frontmatter.get("type") or "").casefold() == "source"
        ):
            target_identities = {
                normalize_source_identity(value)
                for value in _string_list(target_frontmatter.get("sources"))
                if normalize_source_identity(value).startswith("raw/")
            }
            source_identities = {
                normalize_source_identity(value)
                for value in _string_list(source_frontmatter.get("sources"))
                if normalize_source_identity(value).startswith("raw/")
            }
            approved_identity = normalize_source_identity(
                checked.get("approved_source_identity") or ""
            )
            overlap = target_identities & source_identities
            if approved_identity:
                if approved_identity not in target_identities | source_identities:
                    raise ValueError("Approved Source identity is absent from both merge pages.")
                overlap.add(approved_identity)
            if len(overlap) != 1:
                raise ValueError("Source merge requires exactly one approved canonical raw identity.")
            raw_identity = next(iter(overlap))
            if target_identities | source_identities != {raw_identity}:
                raise ValueError(
                    "Source merge pages must resolve to one canonical raw identity."
                )
            memory_root = get_memory_dir().resolve()
            raw_root = (memory_root / "raw").resolve()
            raw_path = (memory_root / Path(raw_identity)).resolve()
            if not raw_path.is_relative_to(raw_root) or not raw_path.is_file():
                raise ValueError(f"Source raw identity is missing or outside raw root: {raw_identity}")
            artifact_hash = hashlib.sha256(raw_path.read_bytes()).hexdigest()
            for frontmatter in (target_frontmatter, source_frontmatter):
                metadata_map = frontmatter.get("source_artifacts") or {}
                if not isinstance(metadata_map, dict):
                    raise ValueError("source_artifacts must be a mapping.")
                metadata = metadata_map.get(raw_identity) or {}
                if not isinstance(metadata, dict):
                    raise ValueError(f"source_artifacts metadata must be a mapping for {raw_identity}.")
                declared_hash = str(metadata.get("sha256") or metadata.get("content_hash") or "")
                if declared_hash and declared_hash != artifact_hash:
                    raise ValueError(f"Source artifact hash changed for {raw_identity}.")
            checked["source_identity"] = raw_identity
            checked["source_artifact_hash"] = artifact_hash

            if backlink_index is None:
                backlink_index = build_wiki_backlink_index(wiki_dir)
            excluded_pages = {
                normalize_page_key_identity(target_key),
                normalize_page_key_identity(source_key),
            }
            backlinks = [
                {
                    "page_key": page_key,
                    "projection_hash": projection_hash,
                }
                for page_identity, page_key, projection_hash in backlink_index.get(
                    normalize_page_key_identity(source_key),
                    (),
                )
                if page_identity not in excluded_pages
            ]
            checked["backlink_manifest"] = backlinks
            if backlinks:
                raise ValueError(
                    f"Source merge has {len(backlinks)} direct backlink(s); rewrite is required before merge."
                )

        merged_content = merge_markdown_content(
            target_bytes.decode("utf-8"),
            source_bytes.decode("utf-8"),
            source_key=source_key,
            source_metadata_conflict_policy=checked.get(
                "source_metadata_conflict_policy"
            ),
        )
        frontmatter, body = split_frontmatter(merged_content)
        validate_schema(frontmatter, body, target_path.name)
        checked["preflight_state"] = "passed"
    except Exception as exc:
        checked["preflight_state"] = "blocked"
        checked["preflight_errors"] = [f"{type(exc).__name__}: {exc}"]
    return checked
