"""_NON_CLAIM_ARTIFACTS _collapse_text classify_non_claim_text

Split out of claim_extractor so that a lower layer can use it without importing a
handler. The cluster is closed under intra-module references; claim_extractor
re-imports these names for its remaining code.
"""

from __future__ import annotations

import re


_NON_CLAIM_ARTIFACTS = (
    (
        "system_directive",
        re.compile(
            r"^(?:\([^)]{1,100}\)\s*)?\*?\[system directive:[^\]]+\]\*?\.?$",
            re.IGNORECASE,
        ),
    ),
    (
        "generated_stub",
        re.compile(
            r"^this is an auto-generated stub page to prevent broken links from .+?\.?$",
            re.IGNORECASE,
        ),
    ),
    (
        # Same sentence with the "from X" target dropped. It still says nothing,
        # so treating it as a claim publishes a maintenance notice as knowledge.
        "generated_stub_truncated",
        re.compile(
            r"^this is an auto-generated stub page to prevent broken links\.?$",
            re.IGNORECASE,
        ),
    ),
    (
        # Alternate wording emitted by the link-repair pass; the third known
        # spelling, and the one that produced dated Observation events.
        "generated_broken_link_stub",
        re.compile(
            r"^auto-generated stub to resolve broken link from .+?\.?$",
            re.IGNORECASE,
        ),
    ),
    (
        "generated_reshaped_stub",
        re.compile(
            r"^auto-generated stub for (?P<subject>[^.!?。！？]{1,160})\. "
            r"\(last reshaped: \d{4}-\d{2}-\d{2}\)$",
            re.IGNORECASE,
        ),
    ),
    (
        "generated_entity_stub",
        re.compile(
            r"^(?P<subject>[^.!?。！？]{1,160}) auto-generated stub\.$",
            re.IGNORECASE,
        ),
    ),
    (
        "schema_migration_marker",
        re.compile(
            r"^(?:\[[^\]]+\]\s*){0,2}node auto-migrated to v\d+(?:\.\d+)* schema\.?$",
            re.IGNORECASE,
        ),
    ),
    ("decoder_metadata", re.compile(r"^read mode:\s*utf-8(?:-ignore)?\s*$", re.IGNORECASE)),
    (
        "semantic_summary_placeholder",
        re.compile(
            r"^(?:\(semantic summary\)\s*)?\(?to be generated by llm during review/synthesis\)?$",
            re.IGNORECASE,
        ),
    ),
)

def _collapse_text(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()

def classify_non_claim_text(
    raw_text: str, cleaned_text: str = "", *, page_key: str = "",
) -> str | None:
    """Recognize whole-block maintenance prose; entity stubs require page identity."""
    text = _collapse_text(cleaned_text or raw_text)
    for reason, pattern in _NON_CLAIM_ARTIFACTS:
        match = pattern.fullmatch(text)
        if not match:
            continue
        if "subject" in match.groupdict():
            page = str(page_key or "").replace("\\", "/").rsplit("/", 1)[-1]
            if page.endswith(".md"):
                page = page[:-3]
            short_page = re.sub(
                r"^(?:Concept|Product|Institution|Event|Policy|Vendor|Entity|Source)_",
                "", page,
            )
            subject = _collapse_text(match.group("subject").replace("_", " ")).casefold()
            identities = {
                _collapse_text(value.replace("_", " ")).casefold()
                for value in (page, short_page) if value
            }
            if subject not in identities:
                continue
        return reason
    return None
