import json
import re

import yaml

from vector_lake.wiki_utils import split_frontmatter


def _as_list(value) -> list:
    if value is None:
        return []
    if isinstance(value, list):
        return list(value)
    return [value]


def _demote_headings(body: str) -> str:
    """Keep source labels without leaving heading tokens that mimic a timeline section."""
    lines = []
    for line in body.splitlines():
        match = re.match(r"^(#{1,6})(\s+.*)$", line)
        if match:
            line = f"**{match.group(2).strip()}**"
        lines.append(line)
    return "\n".join(lines).strip()


def _item_key(value) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)


def _union_list(left, right) -> list:
    merged = []
    seen = set()
    for value in [*_as_list(left), *_as_list(right)]:
        key = _item_key(value)
        if key not in seen:
            seen.add(key)
            merged.append(value)
    return merged


def _is_generic_source(value) -> bool:
    normalized = "".join(character for character in str(value).casefold() if character.isalnum())
    return normalized in {
        "sourceautofixed",
        "sourceautogenerated",
        "sourcegenerated",
        "sourcestub",
        "sourcetemplate",
    }


def _merge_source_artifacts(left, right) -> dict:
    if left is None:
        left = {}
    if right is None:
        right = {}
    if not isinstance(left, dict) or not isinstance(right, dict):
        raise ValueError("source_artifacts must be mappings when supplied.")
    merged = {key: dict(value) if isinstance(value, dict) else value for key, value in left.items()}
    for raw_ref, metadata in right.items():
        if raw_ref not in merged:
            merged[raw_ref] = dict(metadata) if isinstance(metadata, dict) else metadata
            continue
        if not isinstance(merged[raw_ref], dict) or not isinstance(metadata, dict):
            if merged[raw_ref] != metadata:
                raise ValueError(f"Conflicting source_artifacts metadata for {raw_ref}.")
            continue
        conflicts = {
            key
            for key in set(merged[raw_ref]) & set(metadata)
            if merged[raw_ref][key] != metadata[key]
        }
        if conflicts:
            raise ValueError(
                f"Conflicting source_artifacts metadata for {raw_ref}: {', '.join(sorted(conflicts))}."
            )
        merged[raw_ref] = {**metadata, **merged[raw_ref]}
    return merged


def _is_backlog_placeholder(frontmatter: dict, body: str) -> bool:
    categories = {str(item).casefold() for item in _as_list(frontmatter.get("categories"))}
    return (
        str(frontmatter.get("topic_cluster") or "").casefold() == "raw_ingest_backlog"
        or "raw_ingest_backlog" in categories
        or "historical awaiting_subagent backlog" in body.casefold()
    )


def _validate_scalar_contract(left: dict, right: dict, right_is_backlog: bool) -> None:
    if right_is_backlog:
        return
    neutral = {"", "general", "unknown", "unspecified", "edge", "derived"}
    for field in ("domain", "topic_cluster", "evidence_tier", "strategic_scope"):
        left_value = str(left.get(field) or "").strip()
        right_value = str(right.get(field) or "").strip()
        if (
            left_value
            and right_value
            and left_value.casefold() not in neutral
            and right_value.casefold() not in neutral
            and left_value.casefold() != right_value.casefold()
        ):
            raise ValueError(f"Conflicting Source scalar field {field}: {left_value} != {right_value}.")


def merge_markdown_content(
    left_content: str,
    right_content: str,
    source_key: str | None = None,
) -> str:
    """Return a merged left page without mutating either source file."""
    left_frontmatter, left_body = split_frontmatter(left_content)
    right_frontmatter, right_body = split_frontmatter(right_content)
    if not left_frontmatter:
        raise ValueError("The merge target has no valid YAML frontmatter.")
    if not right_frontmatter:
        raise ValueError("The merge source has no valid YAML frontmatter.")

    right_is_backlog = _is_backlog_placeholder(right_frontmatter, right_body)
    _validate_scalar_contract(left_frontmatter, right_frontmatter, right_is_backlog)

    left_aliases = _as_list(left_frontmatter.get("aliases"))
    right_aliases = _as_list(right_frontmatter.get("aliases"))
    if source_key:
        right_aliases.append(source_key)
    right_title = str(right_frontmatter.get("title") or "").strip()
    if right_title:
        right_aliases.append(right_title)
    for alias in right_aliases:
        if alias and alias not in left_aliases:
            left_aliases.append(alias)
    left_frontmatter["aliases"] = left_aliases

    merged_sources = _union_list(
        left_frontmatter.get("sources"),
        right_frontmatter.get("sources"),
    )
    if any(str(value).replace("\\", "/").lstrip("[ ").startswith("raw/") for value in merged_sources):
        merged_sources = [value for value in merged_sources if not _is_generic_source(value)]
    left_frontmatter["sources"] = merged_sources

    for field in ("tags", "tension_edges"):
        merged = _union_list(left_frontmatter.get(field), right_frontmatter.get(field))
        if merged or field in left_frontmatter or field in right_frontmatter:
            left_frontmatter[field] = merged

    categories = _union_list(
        left_frontmatter.get("categories"),
        [] if right_is_backlog else right_frontmatter.get("categories"),
    )
    if categories:
        left_frontmatter["categories"] = categories

    source_artifacts = _merge_source_artifacts(
        left_frontmatter.get("source_artifacts"),
        right_frontmatter.get("source_artifacts"),
    )
    if source_artifacts:
        left_frontmatter["source_artifacts"] = source_artifacts

    right_relations = _as_list(right_frontmatter.get("relations"))
    left_relations = _as_list(left_frontmatter.get("relations"))
    if right_relations and not right_is_backlog and right_relations != left_relations:
        raise ValueError("Source merge requires typed Markdown relation migration before merging YAML relations.")

    rendered_frontmatter = yaml.safe_dump(
        left_frontmatter,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
    )
    source_label = right_title or source_key or "merged source"
    source_block = "" if right_is_backlog else f"## Merged from {source_label}\n{_demote_headings(right_body)}"
    if not source_block:
        merged_body = left_body.strip()
    else:
        timeline_match = re.search(r"(?m)^## 2\. 证据时间线.*$", left_body)
        if timeline_match:
            prefix = left_body[: timeline_match.start()].rstrip()
            timeline = left_body[timeline_match.start() :].lstrip()
            merged_body = f"{prefix}\n\n{source_block}\n\n{timeline}"
        else:
            merged_body = f"{left_body.strip()}\n\n{source_block}"
    return (
        f"---\n{rendered_frontmatter}---\n"
        f"{merged_body.strip()}\n"
    )
