import sqlite3
from pathlib import Path
from datetime import datetime

# Paths
meta_dir = Path(r"C:\Users\shich\.gemini\MEMORY\wiki\.meta")
db_path = meta_dir / "vector_lake.db"
output_md = meta_dir / "DB_Topology_Snapshot.md"

def generate_snapshot():
    if not db_path.exists():
        print(f"Database not found at {db_path}")
        return

    conn = sqlite3.connect(str(db_path))
    cursor = conn.cursor()

    # 1. Table Row Counts
    tables = [
        "entities", "claims", "evidence", "sources", "change_sets",
        "governance_queue", "alias_registry", "operational_memory",
        "claim_graph_nodes", "claim_graph_edges", "timeline_events"
    ]
    
    counts = {}
    for table in tables:
        try:
            cursor.execute(f"SELECT COUNT(*) FROM {table}")
            counts[table] = cursor.fetchone()[0]
        except sqlite3.OperationalError:
            counts[table] = "N/A"

    # 2. Top Hub Nodes (Entities with most edges)
    # Using claim_graph_edges where relations involve nodes
    try:
        cursor.execute("""
            SELECT source_id, COUNT(*) as edge_count
            FROM claim_graph_edges
            GROUP BY source_id
            ORDER BY edge_count DESC
            LIMIT 10
        """)
        top_hubs_out = cursor.fetchall()
    except sqlite3.OperationalError:
        top_hubs_out = []

    try:
        cursor.execute("""
            SELECT target_id, COUNT(*) as edge_count
            FROM claim_graph_edges
            GROUP BY target_id
            ORDER BY edge_count DESC
            LIMIT 10
        """)
        top_hubs_in = cursor.fetchall()
    except sqlite3.OperationalError:
        top_hubs_in = []

    conn.close()

    # 3. Format as Markdown
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    md_content = f"# Vector Lake: DB Topology Snapshot\n\n"
    md_content += f"**Generated At:** {now_str}\n"
    md_content += f"**Database Path:** `{db_path}`\n\n"

    md_content += "## 1. Table Statistics (宏观数据规模)\n\n"
    md_content += "| Table Name | Row Count | Description |\n"
    md_content += "| :--- | :--- | :--- |\n"
    md_content += f"| entities | {counts.get('entities')} | 独立概念与实体节点 |\n"
    md_content += f"| claims | {counts.get('claims')} | 抽取出的高阶语义断言 |\n"
    md_content += f"| evidence | {counts.get('evidence')} | 支撑断言的原文证据块 |\n"
    md_content += f"| claim_graph_edges | {counts.get('claim_graph_edges')} | 逻辑图谱中的关系边 |\n"
    md_content += f"| timeline_events | {counts.get('timeline_events')} | 按时间线抽取的核心事件 |\n"
    md_content += f"| governance_queue | {counts.get('governance_queue')} | 待解决的图谱冲突/合并任务 |\n"
    md_content += f"| alias_registry | {counts.get('alias_registry')} | 同义词重定向映射 |\n"

    md_content += "\n## 2. Top Hub Nodes (高连通性核心枢纽)\n\n"
    md_content += "### 最活跃的发起节点 (Top Sources)\n"
    for hub in top_hubs_out:
        md_content += f"- **{hub[0]}**: {hub[1]} edges\n"
        
    md_content += "\n### 被高频指向的目标节点 (Top Targets)\n"
    for hub in top_hubs_in:
        md_content += f"- **{hub[0]}**: {hub[1]} edges\n"

    md_content += "\n---\n"
    md_content += "> *This file is automatically generated by the Vector Lake Virtual Materialized View engine.*"

    with open(output_md, "w", encoding="utf-8") as f:
        f.write(md_content)
        
    print(f"Snapshot generated successfully at {output_md}")

if __name__ == "__main__":
    generate_snapshot()